#!/bin/sh
# Author=wulishui

[ -n "$(pidof oafd)" ] && { echo "$(grep -c ' 1 ' /tmp/dev_list 2>/dev/null)" ; exit ; }

wanr=`ip route 2>/dev/null |grep -c '^default'`
olr=`cat /proc/net/arp 2>/dev/null |grep -c '0x2'`
echo "$((olr-wanr))"

