#!/bin/sh

NETMODE=$(uci -q get modemconfig.@modem[0].mode)
GET_GSM=$(uci -q get modemconfig.@modem[0].gsm_band)
GET_3G=$(uci -q get modemconfig.@modem[0].3g_band)
GET_LTE_FDD=$(uci -q get modemconfig.@modem[0].lte_band_fdd)
GET_LTE_TDD=$(uci -q get modemconfig.@modem[0].lte_band_tdd)
SLOT=$(/usr/bin/mmcli -L | awk '{print $1}' | awk -F [\/] '{print $NF}')

BAND2G=""
BAND3G=""
BAND4G=""

# Control empty bands
get_bands(){
	if [ "$GET_BAND" ]; then
                continue
        else
                return
        fi

}

# Network Mode prefs
set_mode(){
	case $NETMODE in
		2g) 
			NMODE=2g
			PREFMODE=none
		;;
		3g)
			NMODE=3g
			PREFMODE=none
		;;
		4g)
			NMODE=4g
			PREFMODE=none
		;;
		3gp2g)
			NMODE="2g|3g"
			PREFMODE=2g
		;;
		p3g2g)
			NMODE="2g|3g"
			PREFMODE=3g
		;;
		p4g3g2g)
			NMODE="2g|3g|4g"
			PREFMODE="4g"
		;;
		4gp3g2g)
			NMODE="2g|3g|4g"
			PREFMODE=3g
		;;
		4g3gp2g)
			NMODE="2g|3g|4g"
			PREFMODE=2g
		;;
		p4g3g)
			NMODE="4g|3g"
			PREFMODE="4g"
		;;
		4gp3g)
			NMODE="4g|3g"
			PREFMODE="3g"
		;;
	esac
}

# Select 2G bands
set_2g(){
	GET_BAND="$GET_GSM"
	get_bands
	for g in $GET_BAND; do
		case $g in
			3) BAND="dcs" ;;
			8) BAND="egsm" ;;
			*) BAND="" ;;
		esac
		BAND2G="$BAND|$BAND2G"
	done
}

# Select 3G bands
set_3g(){
	GET_BAND="$GET_3G"
	get_bands
	for g in $GET_BAND; do
        	case $g in
        	        1) BAND="utran-1" ;;
	                8) BAND="utran-8" ;;
			9) BAND="utran-9" ;;
	                *) BAND="" ;;
	        esac
	        BAND3G="$BAND|$BAND3G"
	done
}

# Select 4G FDD bands
set_4g_fdd(){
	GET_BAND="$GET_LTE_FDD"
	get_bands
	for g in $GET_BAND; do
	        case $g in
			1) BAND="eutran-1" ;;
		        3) BAND="eutran-3" ;;
			5) BAND="eutran-5" ;;
		        7) BAND="eutran-7" ;;
			8) BAND="eutran-8" ;;
			20) BAND="eutran-20" ;;
		esac
		BAND4GFDD="$BAND|$BAND4GFDD"
	done
}

# Select 4G TDD bands
set_4g_tdd(){
	GET_BAND="$GET_LTE_TDD"
	get_bands
	for g in $GET_BAND; do
		case $g in
			38) BAND="eutran-38" ;;
			40) BAND="eutran-40" ;;
			41) BAND="eutran-41" ;;
	        esac
	        BAND4GTDD="$BAND|$BAND4GTDD"
	done
}
# Reset to defautls bands
reset_to_defaults(){
	DEFBAND=""
	SUPPORTED_BANDS="$(echo $(mmcli -J -m $SLOT | jsonfilter -e '@["modem"]["generic"]["supported-bands"][*]'))"
	for g in $SUPPORTED_BANDS; do
		DEFBAND="$g|$DEFBAND"
	done
	DEFBAND=$(echo $DEFBAND | sed 's/.$//')
}

set_2g
set_3g
set_4g_fdd
set_4g_tdd

if [ $BAND4GFDD ]; then
	BAND4G=$BAND4GFDD
fi
if [ $BAND4GTDD ]; then
	BAND4G=$BAND4GTDD
fi
if [ $BAND4GTDD ] && [ $BAND4GFDD ]; then
        BAND4G=${BAND4GTDD}${BAND4GFDD}
fi
	
BAND=$(echo ${BAND2G}${BAND3G}${BAND4G} | sed 's/.$//')

# Select band
if [ "$BAND" ]; then
	/usr/bin/mmcli -m $SLOT --set-current-bands="$BAND"
else
	reset_to_defaults
	/usr/bin/mmcli -m $SLOT --set-current-bands="$DEFBAND"
fi

# Select netmode
if [ "$NETMODE" ]; then
	set_mode
	/usr/bin/mmcli -m $SLOT --set-allowed-modes="$NMODE" --set-preferred-mode=$PREFMODE
else
	/usr/bin/mmcli -m $SLOT --set-allowed-modes="4g|3g" --set-preferred-mode=4g
fi
