#
# Copyright (C) 2023 wulishui <wulishui@msn.com>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci for cpu usage
LUCI_DEPENDS:=+sysstat +bash
LUCI_PKGARCH:=all
PKG_VERSION:=v23.4.12
PKG_RELEASE:=2222

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

