"use strict";
"require view";
"require ui";
"require uci";
"require rpc";
"require utils.hub-api as hubApi";
"require utils.asset-upload as assetUpload";
"require utils.theme-preview as themePreview";

// Theme Store: marketplace grid + detail drawer + share panel + "my shares"
// management. Built-in presets render from a local JSON copy
// (htdocs/.../aurora/presets.json, generated by scripts/gen-presets.mjs) so
// the store keeps working offline; they apply through the local
// apply_theme_preset rpcd path, never the hub.
//
// Every piece of hub-sourced text (name, author, palette hex values,
// layout/typography strings, toolbar urls) is untrusted: it is rendered only
// via E()'s textContent-safe children, document.createTextNode, or explicit
// style property assignment -- never through innerHTML. Palette hex values
// are additionally sanitised before being interpolated into color-mix()
// strings (see safeHex).
//
// UX zero-burden rule: all user-facing copy describes results only
// ("Applied", "Restore previous configuration", "This configuration can't
// be applied", "Published", "Updated", "Deleted"). Mechanism words (job,
// schema, token, pending, bad_payload) never surface -- see
// applyErrorMessage/restoreErrorMessage/shareErrorMessage/
// updateErrorMessage/deleteErrorMessage below, which map every backend
// error code to friendly copy instead of echoing it.

const SWATCH_KEYS = ["bg", "surface", "text", "brand"];

// build_share_payload skips assets whose filename is still the factory one --
// an unmodified slot means the user never customised it, so nothing is
// uploaded. The manifest must skip exactly the same names, or it would
// promise to share a logo that never leaves the box.
//
// This list is duplicated from root/usr/libexec/rpcd/luci.aurora (the case
// statement in build_share_payload). tests/gallery-view.test.mjs asserts the
// two stay identical.
const FACTORY_ASSET_NAMES = [
  "logo.svg",
  "favicon.ico",
  "app-icon-192x192.png",
  "app-icon-512x512.png",
  "apple-touch-icon.png",
];

const loginBgFilename = (value) => {
  const match = /^url\('\/luci-static\/aurora\/images\/([^']+)'\)$/.exec(value || "");
  return match ? match[1] : "";
};

// Mirrors build_share_payload's own guard: a name containing "/" or ".." never
// makes it into a share, so it must not show up in the manifest either.
const isSharedAssetName = (name) =>
  !!name &&
  name.indexOf("/") === -1 &&
  name.indexOf("..") === -1 &&
  FACTORY_ASSET_NAMES.indexOf(name) === -1;

// build_share_payload validates every toolbar item against the hub's own
// limits and silently skips the ones that fail, then stops after 12 accepted
// items. The local toolbar editor (theme.js) only requires each field to be
// non-empty, so a config built entirely through this package's own UI can hold
// items the share leaves behind -- a title over 30 characters or carrying an
// apostrophe, a url with neither a scheme nor a leading slash, an icon name
// outside [A-Za-z0-9._-]. Counting the raw sections would promise shortcuts
// that never go out, so the checks below mirror the shell's exactly.
//
// Duplicated from root/usr/libexec/rpcd/luci.aurora, build_share_payload:
// the cap at line 631, the per-item checks at lines 637-660.
const MAX_SHARED_TOOLBAR_ITEMS = 12;

// Mirrors has_control_char and the `tr -d '[:cntrl:]'` title pass: the title is
// stripped and then measured, every other field is rejected outright.
const CONTROL_CHAR_RE = /[\u0000-\u001f\u007f]/;
const stripControlChars = (value) =>
  String(value == null ? "" : value).replace(/[\u0000-\u001f\u007f]/g, "");

// The shell measures every length with `${#var}`, which under BusyBox ash (no
// UTF-8 locale) counts octets, while a JavaScript string's .length counts
// UTF-16 code units. An 11-character Chinese label is 33 octets: the shell
// drops that item while the browser would still count it, so the manifest
// would promise a shortcut that never goes out -- exactly the drift mirroring
// the shell is meant to prevent. Both limits below measure the encoded form,
// the way the shell sees it.
const utf8Length = (value) =>
  new TextEncoder().encode(String(value == null ? "" : value)).length;

const isSharedToolbarItem = (item) => {
  const title = stripControlChars(item && item.title);
  const titleLength = utf8Length(title);
  if (!titleLength || titleLength > 30 || title.indexOf("'") !== -1)
    return false;

  const url = String((item && item.url) || "");
  if (CONTROL_CHAR_RE.test(url) || utf8Length(url) > 200) return false;
  if (url.indexOf("//") === 0) return false;
  if (
    url.indexOf("http://") !== 0 &&
    url.indexOf("https://") !== 0 &&
    url.indexOf("/") !== 0
  )
    return false;

  const icon = String((item && item.icon) || "");
  if (icon && (icon.length > 64 || !/^[A-Za-z0-9._-]+$/.test(icon)))
    return false;

  const enabled = item && item.enabled;
  return enabled === "0" || enabled === "1";
};

const NAV_TYPE_LABELS = {
  "mega-menu": _("Mega Menu"),
  dropdown: _("Dropdown"),
  sidebar: _("Sidebar"),
};

// Built-in presets: ids must match root/usr/share/aurora/*.template and the
// labels reuse the exact msgids the old preset dropdown used, so existing
// translations keep working.
const BUILTIN_PRESETS = [
  { id: "default", label: _("Default") },
  { id: "monochrome", label: _("Monochrome") },
  { id: "sage-green", label: _("Sage Green") },
  { id: "amber-sand", label: _("Amber Sand") },
  { id: "sky-blue", label: _("Sky Blue") },
];

// Official hub seeds mirror the built-in presets ("Default · 默认" by
// "Aurora", ...). Until the hub exposes a builtin_id field, hide them by the
// only stable signal they carry so the same theme never shows up twice.
const BUILTIN_SEED_RE = /^(Default|Sage Green|Amber Sand|Monochrome|Sky Blue)\b/;
const isBuiltinSeed = (item) =>
  (item && item.author) === "Aurora" && BUILTIN_SEED_RE.test(item.name || "");

const callApplyThemePreset = rpc.declare({
  object: "luci.aurora",
  method: "apply_theme_preset",
  params: ["name"],
});

// ---------------------------------------------------------------------------
// Palette helpers

// A list row carries `preview`: a structural subset of the stored payload
// that reuses payload's own key names and types. So one accessor can serve
// both a card (preview) and the drawer (full payload), and neither can
// describe the same configuration differently.
//
// Three shapes have to be handled, newest first:
//   1. `item.preview`   -- a list row from a hub with the projection
//   2. `item.payload`   -- a detail row (always complete)
//   3. `item.palette`   -- a list row from a hub without the projection.
//      DEPRECATED on the hub side and kept only so a new client still works
//      against an old one.
const previewOf = (item) => {
  const preview = item && item.preview;
  return preview && typeof preview === "object" && !Array.isArray(preview)
    ? preview
    : null;
};

const paletteOf = (item) => {
  const preview = previewOf(item);
  const flat =
    (preview && preview.colors) ||
    (item && item.payload && item.payload.colors) ||
    null;
  if (flat) {
    const pick = (mode) =>
      SWATCH_KEYS.reduce((acc, key) => {
        acc[key] = flat[mode + "_" + key] || "";
        return acc;
      }, {});
    return { light: pick("light"), dark: pick("dark") };
  }
  if (item && item.palette) return item.palette;
  return { light: {}, dark: {} };
};

// Hub-sourced hex values are untrusted free text; the shared preview module
// sanitises every value before it can reach a color-mix() expression.
const safeHex = (value, fallback) => themePreview.safeHex(value, fallback);
// Forwarding opts is what makes nav_type visible at all -- an earlier version
// dropped the second parameter, which is why buildMini's sidebar branch never
// rendered.
const buildDuo = (palette, opts) => themePreview.buildDuo(palette, opts);

// nav_type used to exist only on the detail payload, so every community card
// drew a top bar regardless of what the configuration actually did. It is on
// the list row now (preview.layout), so cards draw the real shape.
const navOf = (item) => {
  const preview = previewOf(item);
  const layout =
    (preview && preview.layout) ||
    (item && item.payload && item.payload.layout) ||
    {};
  return layout.nav_type || "";
};

// The approved asset entries, whichever shape the item came in. A detail row
// already carries `assets` with urls; `payload.assets` is the author's
// manifest and may still name unapproved kinds, so it is the last resort and
// carries no url.
const assetsOf = (item) => {
  const preview = previewOf(item);
  const list =
    (preview && preview.assets) ||
    (item && item.assets) ||
    (item && item.payload && item.payload.assets);
  return Array.isArray(list) ? list : [];
};

const assetKindsOf = (item) =>
  assetsOf(item)
    .map((asset) => (asset && asset.kind) || "")
    .filter(Boolean);

// Only logo_svg is ever fetched for display. login_bg stays a label:
// /assets/:id/:kind streams the original image (capped at 2 MiB) and a full
// page of 24 cards would pull one each.
//
// hubAssetUrl validates the hub-supplied relative path and prepends the base
// -- this file must not know the hub's hostname, and must not concatenate an
// untrusted path itself.
const logoUrlOf = (item) => {
  const entry = assetsOf(item).find(
    (asset) => asset && asset.kind === "logo_svg" && asset.url,
  );
  return entry ? hubApi.hubAssetUrl(entry.url) : "";
};

// What a mini preview needs to draw a specific configuration.
const previewOpts = (item) => ({ nav: navOf(item), logo: logoUrlOf(item) });

const buildDotRow = (palette) =>
  E(
    "span",
    { style: "display:inline-flex;gap:3px;" },
    [
      (palette.light || {}).brand,
      (palette.light || {}).bg,
      (palette.dark || {}).brand,
      (palette.dark || {}).bg,
    ].map((hex) => {
      const dotEl = E("span", {
        style:
          "width:11px;height:11px;border-radius:50%;" +
          "border:1px solid var(--hairline, rgba(0,0,0,0.15));",
      });
      dotEl.style.backgroundColor = safeHex(hex, "transparent");
      return dotEl;
    }),
  );

// The 460px drawer is wide enough to show both modes whole; the diagonal
// duo belongs on cards, where there is no room for two panes.
const buildPane = (label, palette, opts) =>
  E("figure", { class: "aurora-store-pane" }, [
    E("div", { class: "aurora-store-pane-box" }, [
      themePreview.buildMini(palette || {}, opts),
    ]),
    E("figcaption", {}, label),
  ]);

const buildPanes = (palette, opts) =>
  E("div", { class: "aurora-store-panes" }, [
    buildPane(_("Light"), (palette || {}).light, opts),
    buildPane(_("Dark"), (palette || {}).dark, opts),
  ]);

// ---------------------------------------------------------------------------
// "What this config carries beyond the preview"
//
// Colors, nav_type and the logo are drawn; everything else is listed here as
// glyph+text. Cards and the drawer share one builder: the list row now
// carries the same layout/typography/toolbar/assets shapes the detail
// payload does, and two builders had already drifted into cards saying
// "Includes custom content" while the drawer itemised the pieces.
//
// Still deliberately no login-background thumbnail: that endpoint streams the
// original image, and a page of cards would each pull one.

const SITE_ICON_KINDS = ["favicon_png", "favicon_ico"];
const APP_ICON_KINDS = ["pwa_icon_192", "pwa_icon_512"];

// One set of names for the four image slots a configuration can carry. The
// drawer (what a shared config brings) and the share manifest (what your own
// config sends) describe the same payload, so they must not invent separate
// words for it -- two literal lists had already drifted into "Background" in
// one place and "Login Background" in the other, on the same page.
const ASSET_LABELS = {
  logo: _("Logo"),
  siteIcon: _("Site Icon"),
  appIcon: _("App Icon"),
  loginBg: _("Login Background"),
};

// typography.font_sans is a preset id ("geist-sans"); struct_font_sans is the
// stack the browser actually uses. Show the family, never the id.
const firstFontFamily = (stack) =>
  String(stack || "")
    .split(",")[0]
    .trim()
    .replace(/^["']|["']$/g, "");

// struct_radius_base is a continuous 0-1.5rem slider, so there are no existing
// tier names to reuse -- these are the store's own, with the exact value kept
// in the tooltip and the detail table.
const RADIUS_TIERS = [
  { below: 0.001, label: _("Square corners") },
  { below: 0.376, label: _("Small corners") },
  { below: 0.751, label: _("Rounded corners") },
  { below: Infinity, label: _("Large corners") },
];

const radiusLabel = (value) => {
  const rem = parseFloat(value);
  if (!isFinite(rem) || rem < 0) return "";
  const tier = RADIUS_TIERS.find((entry) => rem < entry.below);
  return tier ? tier.label : "";
};

const buildTile = (glyph, label, title) => {
  const glyphEl = E("span", { class: "g" });
  glyphEl.appendChild(
    typeof glyph === "string" ? document.createTextNode(glyph) : glyph,
  );
  const el = E("span", { class: "aurora-store-tile" }, [
    glyphEl,
    E("span", {}, [document.createTextNode(label)]),
  ]);
  if (title) el.setAttribute("title", title);
  return el;
};

// The Logo tile draws the real logo in the same 20x20 glyph box the ◆ would
// occupy, and falls straight back to that ◆ if the image cannot be loaded --
// same builder as the preview's brand square, so the two states can never
// diverge. SECURITY: <img src> only; see theme-preview.js.
const logoGlyph = (url) =>
  themePreview.logoImage(
    url,
    document.createTextNode("◆"),
    "width:15px;height:15px;object-fit:contain;display:block;",
  );

const buildTiles = (entries) =>
  E(
    "div",
    { class: "aurora-store-tiles" },
    entries.map((entry) => buildTile(entry.glyph, entry.label, entry.title)),
  );

// Also the fallback for a configuration whose payload carries nothing beyond
// its colors -- the same tile, so the two can never say it differently.
const buildBuiltinTiles = () =>
  buildTiles([
    {
      glyph: "◑",
      label: _("Colors only"),
      title: _("Replaces the light and dark colors; everything else stays as it is."),
    },
  ]);

// A hub that predates the preview projection sends a list row with no
// layout, typography, toolbar or assets at all -- assets_status is the only
// signal it carries. Saying "Colors only" there would be a lie, so that case
// keeps the coarse tile it always had.
const buildLegacyCardTiles = (item) => {
  const status = item && item.assets_status;
  if (!status || status === "none") return null;
  return buildTiles([
    {
      glyph: "◆",
      label: _("Includes custom content"),
      title: _("Open this configuration to see everything it carries."),
    },
  ]);
};

// 一份配置在颜色之外还带了什么,只在这里数一次。卡片只画 glyph、抽屉画完整
// tiles 并且滤掉已经在"布局与排版"和"快捷方式"里说过的那几种 —— 两个消费者,
// 一张表。`kind` 就是给消费者过滤用的。
//
// 返回 null 表示这行来自没有 preview 投影的老 hub,调用方退回
// buildLegacyCardTiles;返回空数组表示这份配置确实只带了颜色。
const tileEntriesFor = (item) => {
  const preview = previewOf(item);
  const source = preview || (item && item.payload);
  if (!source) return null;

  const typography = source.typography || {};
  const layout = source.layout || {};
  // Both toolbar and assets are hub-sourced and therefore untrusted shapes: a
  // hub (or anything sitting between it and the router) answering with
  // assets: "logo_svg" would otherwise throw inside the promise that renders
  // the drawer, leaving it stuck on "Loading theme details…" forever.
  const toolbar = Array.isArray(source.toolbar) ? source.toolbar : [];
  const kinds = assetKindsOf(item);

  const entries = [];

  const family = firstFontFamily(typography.struct_font_sans);
  if (family)
    entries.push({
      kind: "font",
      glyph: "Aa",
      label: family,
      title:
        family +
        (firstFontFamily(typography.struct_font_mono)
          ? " · " + firstFontFamily(typography.struct_font_mono)
          : ""),
    });

  const radius = radiusLabel(layout.struct_radius_base);
  if (radius)
    entries.push({
      kind: "radius",
      glyph: "◜",
      label: radius,
      title: layout.struct_radius_base,
    });

  if (kinds.indexOf("logo_svg") !== -1)
    entries.push({
      kind: "logo",
      glyph: logoGlyph(logoUrlOf(item)),
      label: ASSET_LABELS.logo,
      title: _("Custom logo"),
    });

  if (kinds.indexOf("login_bg") !== -1)
    entries.push({
      kind: "loginBg",
      glyph: "▣",
      label: ASSET_LABELS.loginBg,
      title: _("Custom login page background"),
    });

  if (kinds.some((kind) => SITE_ICON_KINDS.indexOf(kind) !== -1))
    entries.push({
      kind: "siteIcon",
      glyph: "◐",
      label: ASSET_LABELS.siteIcon,
      title: _("Custom site icons"),
    });

  if (kinds.some((kind) => APP_ICON_KINDS.indexOf(kind) !== -1))
    entries.push({
      kind: "appIcon",
      glyph: "◐",
      label: ASSET_LABELS.appIcon,
      title: _("Custom app icons"),
    });

  if (toolbar.length)
    entries.push({
      kind: "toolbar",
      glyph: "⌘",
      label: _("Toolbar %d").format(toolbar.length),
      title: _("Floating toolbar shortcuts"),
    });

  return entries;
};

// 卡片上只放前几个 glyph:一行写着"仅颜色"的标签在 252px 宽的卡上占掉整整
// 一行,而它说的东西在抽屉里有完整版本。title 属性留着完整文字。
const CARD_GLYPH_LIMIT = 3;

const buildCardGlyphs = (item) => {
  const entries = tileEntriesFor(item);
  if (!entries || !entries.length) return null;
  return E(
    "span",
    { class: "aurora-store-glyphs" },
    entries.slice(0, CARD_GLYPH_LIMIT).map((entry) => {
      const box = E("span", { title: entry.title || entry.label });
      box.appendChild(
        typeof entry.glyph === "string"
          ? document.createTextNode(entry.glyph)
          : entry.glyph,
      );
      return box;
    }),
  );
};

// 抽屉的"随附内容"。字体和圆角在"布局与排版"那张表里已经写了值,快捷方式
// 自己占一整节 —— 在这里再画一遍就是同一句话说三次。
const BUNDLED_KINDS = ["logo", "loginBg", "siteIcon", "appIcon"];

const buildBundledTiles = (item) => {
  const entries = tileEntriesFor(item);
  if (!entries) return buildLegacyCardTiles(item);
  if (!entries.length) return buildBuiltinTiles();
  const bundled = entries.filter(
    (entry) => BUNDLED_KINDS.indexOf(entry.kind) !== -1,
  );
  return bundled.length ? buildTiles(bundled) : null;
};

// ---------------------------------------------------------------------------
// Shortcuts
//
// 详情以前只写 "Toolbar 4",可 payload.toolbar[] 里 title、url、enabled 一直
// 都在 —— 一个准备把别人的配置装到自己路由器上的人,最该看清楚的就是这四条
// 到底指向哪里。列表行来自 hub 的投影(preview.toolbar)则不带 url:那是详情
// 路径的活,卡片不需要。
//
// SECURITY: 每个 toolbar 条目的 icon 存的是作者路由器上
// /www/luci-static/aurora/images/ 里的文件名,而 hub 只批准六种资产
// (logo_svg / login_bg / favicon_png / favicon_ico / pwa_icon_192 /
// pwa_icon_512,见 root/usr/libexec/rpcd/luci.aurora 的 build_share_payload),
// 快捷方式图标不在其中 —— 那些字节从来没有离开过作者的路由器。为 icon 拼一个
// 路径就是画一张本机没有的图,还是用 hub 给的名字拼的。图标槽因此是一个中性
// 占位符,而真正有用的两列是标题和目标。
const SHORTCUT_GLYPH = "▫";

// A hub field is JSON of whatever type the sender chose to send, not
// whatever the schema promises: a bare number, an array, or an object whose
// toString and valueOf are themselves string-valued keys ({"toString":"x"}
// parses fine and is not callable). String(value) attempts to coerce a value
// to a primitive and throws when neither conversion is callable; treating
// anything that is not already a string as absent sidesteps that coercion
// entirely instead of trying and catching it. Same idiom
// externalToolbarUrls already uses below (typeof entry.url === "string").
const shortcutText = (value) => (typeof value === "string" ? value : "");

// 正则先绑常量,绝不能让字面量紧跟在箭头后面 —— jsmin 会把它当成除号,正则里
// 相邻的两个 "/" 随即被当作行注释吃掉,整个 view 报 "Invalid regular
// expression: missing /"。商店页面真机上就是这样挂的。
// 原委见 docs/DEVELOPMENT.md §11;tests/jsmin-safety.test.mjs 守着这条规则。
const EXTERNAL_URL_RE = /^https?:\/\//;

const isExternalShortcut = (url) => EXTERNAL_URL_RE.test(shortcutText(url));

// 剥掉 scheme,让站外链接读成它的主机名,本地 LuCI 路径原样留着。刻意是字符串
// 手术而不是交给一个 URL 解析构造函数:这是不可信自由文本,只为了显示它没有
// 理由喂给解析器。
//
// 与 isExternalShortcut 共用同一个正则对象是安全的:它没有 g/y 标志,test() 和
// replace() 都不会推进 lastIndex。
const shortcutTarget = (url) => shortcutText(url).replace(EXTERNAL_URL_RE, "");

const buildShortcutRow = (entry) => {
  // Hub storage is JSON, and {"toolbar": [null]} is ordinary valid JSON --
  // Array.isArray passes, .map() still calls this with entry === null, and
  // every entry.x below would throw on that shape. Normalize once, up front,
  // so no later property read needs its own guard. Whatever the schema
  // promises, this is untrusted wire content, not a guarantee.
  entry = entry || {};
  const disabled = entry.enabled === "0";
  const external = isExternalShortcut(entry.url);
  const title = shortcutText(entry.title) + (disabled ? " " + _("(disabled)") : "");
  const children = [
    E("span", { class: "ic" }, [document.createTextNode(SHORTCUT_GLYPH)]),
    E("span", { class: "nm" }, [document.createTextNode(title)]),
    E("span", { class: "to" }, [
      document.createTextNode(shortcutTarget(entry.url)),
    ]),
  ];
  if (external)
    children.push(E("span", { class: "ext", title: _("Opens an external site") }, "↗"));
  return E("li", { class: disabled ? "off" : "" }, children);
};

// 返回 [标题, 列表, ...注脚] 一整节,或者在这份配置没带快捷方式时返回 null。
const buildShortcutList = (toolbar, layout) => {
  const items = Array.isArray(toolbar) ? toolbar : [];
  if (!items.length) return null;

  const nodes = [
    buildDetailHeading(_("Shortcuts %d").format(items.length)),
    E("ul", { class: "aurora-store-sc" }, items.map(buildShortcutRow)),
  ];

  // 带了快捷方式却把工具栏整个关掉是合法的。不说的话这一节就是在承诺
  // 一批不会出现的按钮。
  if (layout && layout.toolbar_enabled === "0")
    nodes.push(
      E(
        "p",
        { class: "aurora-store-sc-note" },
        _("The toolbar itself is turned off in this configuration."),
      ),
    );

  if (items.some((entry) => isExternalShortcut(entry && entry.url)))
    nodes.push(
      E(
        "p",
        { class: "aurora-store-sc-note" },
        _(
          "Links marked ↗ open sites outside your router. You'll be asked to confirm before applying.",
        ),
      ),
    );

  return nodes;
};

const formatDownloads = (n) => {
  const count = Number(n) || 0;
  return count === 1 ? _("1 download") : _("%d downloads").format(count);
};

// 分区标题带一句副标题。它接管了被删掉的那句页头总说明 ——
// "内置" 和 "社区" 各自的性质不一样,一句笼统的话说不到点上,而说明放在
// 它描述的那一组上方才有用。
const buildSectionTitle = (title, hint) =>
  E("div", { class: "aurora-store-section-title" }, [
    E("h3", {}, title),
    E("span", {}, hint),
  ]);

// "正在使用"是一个标记,不是一个词。写着字的药丸在 252px 的卡上占掉一整行
// 的宽度,去说一件描边已经说清楚的事。
//
// 两个形态:压在缩略图角上的实心圆片(缩略图底色是任意的,所以它自带一圈
// surface 描边),和跟在标题文字后面的裸对号。两个都挂 title 属性 —— 一个
// 光秃秃的对号对读屏软件是没有意义的。
const buildCurrentPin = () =>
  E("span", { class: "aurora-store-pin", title: _("In use") }, "✓");

const buildCurrentTick = () =>
  E("span", { class: "aurora-store-tick", title: _("In use") }, "✓");

// ---------------------------------------------------------------------------
// Detail body pieces (drawer)

// LuCI 的 cbi-value 把标签列右对齐。在一个 460px 的抽屉里那就是每个标签和
// 它的值之间隔着一道峡谷 —— 这一页上最难读的东西。一张 <dl>,标签靠左,值
// 靠右,中间没有空档。
//
// 值为空的行整行丢掉:一行写着"间距 -"的东西什么也没说。
const buildKvList = (rows) =>
  E(
    "dl",
    { class: "aurora-store-kv" },
    rows
      .filter((row) => row[1])
      .reduce((nodes, [label, value]) => {
        nodes.push(E("dt", {}, [document.createTextNode(label)]));
        nodes.push(E("dd", {}, [document.createTextNode(value)]));
        return nodes;
      }, []),
  );

const buildDetailHeading = (text) => E("h4", { class: "aurora-store-dt-h" }, text);

// "圆角 · 0.5rem":档位名是读的人想要的,原值是想复现的人需要的。
const radiusJoin = (value) => {
  const label = radiusLabel(value);
  if (!label) return "";
  return value ? label + " · " + value : label;
};

const buildPaletteChips = (item) => {
  const palette = paletteOf(item);
  const chip = (hex) => {
    const swatch = E("span", {
      style:
        "display:inline-block;width:14px;height:14px;border-radius:4px;" +
        "border:1px solid var(--hairline, rgba(0,0,0,0.15));vertical-align:-2px;",
    });
    swatch.style.backgroundColor = safeHex(hex, "transparent");
    return E(
      "span",
      {
        style:
          "display:inline-flex;align-items:center;gap:5px;font-size:0.8em;" +
          "padding:2px 8px;border-radius:6px;background:var(--surface-sunken, rgba(0,0,0,0.04));",
      },
      [swatch, document.createTextNode(safeHex(hex, "-"))],
    );
  };
  const chipRow = (label, mode) =>
    E("div", { class: "aurora-store-pal-row" }, [
      E("span", { class: "l" }, label),
      ...SWATCH_KEYS.map((key) => chip((palette[mode] || {})[key])),
    ]);
  return E("div", { class: "aurora-store-pal" }, [
    chipRow(_("Light"), "light"),
    chipRow(_("Dark"), "dark"),
  ]);
};

// 工具栏开关是布局的一部分,不是"快捷方式"那一节的脚注:一份配置可以一条快捷
// 方式都不带,却仍然决定了工具栏出不出现 —— 内置预设正是这种情况。
//
// 两个值逐一比对,不做查表:layout 来自 hub 是任意 JSON,而 `{1:…,0:…}[值]`
// 会把 "constructor" 这类键读成 Object 原型上的东西,然后被当成一行文案画出来。
const toolbarLabel = (value) =>
  value === "1" ? _("Shown") : value === "0" ? _("Hidden") : "";

// 内置预设和社区配置在这张表里说的是同一件事,所以只有一个构造器。内置抽屉
// 曾经只画一行"导航(此预设不改动)",而那句话现在不成立了 —— 预设带的是一整
// 套外观。
const buildLayoutRows = (layout, typography) =>
  buildKvList([
    [_("Navigation"), NAV_TYPE_LABELS[layout.nav_type] || layout.nav_type],
    [_("Spacing"), layout.struct_spacing],
    [_("Corner Radius"), radiusJoin(layout.struct_radius_base)],
    // 侧边栏外壳是全宽的,主题根本不读这个上限(设置页在 sidebar 下也把这个
    // 控件藏起来)。把它当成这份配置的一个特征写出来就是在描述一个死旋钮。
    [
      _("Content Width"),
      layout.nav_type === "sidebar" ? "" : layout.struct_content_width_centered,
    ],
    [_("Sans Font"), firstFontFamily(typography.struct_font_sans)],
    [_("Mono Font"), firstFontFamily(typography.struct_font_mono)],
    [_("Toolbar"), toolbarLabel(layout.toolbar_enabled)],
  ]);

// typography.font_sans/font_mono 是字体名册里的 id。"default" 和 "system" 解析
// 到路由器上已经有的字形,别的 id 一律是 Fontsource 网络字体:要先下载,下载
// 到之前浏览器渲染的是字体栈里的后备字族。内置卡片写着"离线可用",所以这件事
// 必须说出来,否则一台没有外网的路由器会觉得预设只应用了一半。
const BUNDLED_FONT_IDS = ["default", "system"];

const needsFontDownload = (typography) =>
  ["font_sans", "font_mono"].some(
    (key) =>
      typeof typography[key] === "string" &&
      typography[key] &&
      BUNDLED_FONT_IDS.indexOf(typography[key]) === -1,
  );

const buildDetailBody = (item) => {
  const payload = item.payload || {};
  const layout = payload.layout || {};
  const typography = payload.typography || {};

  const children = [
    E("h3", { class: "aurora-store-dt-title" }, [
      document.createTextNode(item.name || _("Untitled theme")),
    ]),
    E("div", { class: "aurora-store-dt-sub" }, [
      document.createTextNode(
        (item.author || _("Anonymous")) + " · " + formatDownloads(item.downloads),
      ),
    ]),
  ];

  if (item.description)
    children.push(
      E("p", { class: "aurora-store-dt-desc" }, [
        document.createTextNode(item.description),
      ]),
    );

  children.push(
    buildDetailHeading(_("Colors")),
    buildPaletteChips(item),
    buildDetailHeading(_("Layout & Typography")),
    buildLayoutRows(layout, typography),
  );

  const shortcuts = buildShortcutList(payload.toolbar, layout);
  if (shortcuts) children.push(...shortcuts);

  const bundled = buildBundledTiles(item);
  if (bundled) children.push(buildDetailHeading(_("Bundled content")), bundled);

  children.push(
    E(
      "p",
      { class: "aurora-store-dt-foot" },
      _(
        "Your current settings are backed up before applying, and you can roll back with one click afterwards.",
      ),
    ),
  );

  return E("div", {}, children);
};

// Toolbar entries that point off-box are the one part of a config that can
// surprise a user after the fact (an admin panel bookmark, a vendor link).
// Anything else in the payload is inert data, so only these need a plaintext
// callout before applying.
const externalToolbarUrls = (payload) => {
  const toolbar = (payload && Array.isArray(payload.toolbar)) ? payload.toolbar : [];
  return toolbar
    .filter(
      (entry) =>
        entry &&
        typeof entry.url === "string" &&
        (entry.url.startsWith("http://") || entry.url.startsWith("https://")),
    )
    .map((entry) => entry.url);
};

// ---------------------------------------------------------------------------
// Result-only error copy

const APPLY_ERROR_COPY = {
  invalid_id: _("This theme is no longer available."),
  hub_unreachable: _("Couldn't reach the theme store. Please try again."),
  bad_payload: _("This configuration can't be applied."),
  job_not_found: _("Applying timed out. Please try again."),
};

const applyErrorMessage = (code) =>
  APPLY_ERROR_COPY[code] || _("This configuration can't be applied.");

const RESTORE_ERROR_COPY = {
  no_backup: _("There's nothing to restore yet."),
};

const restoreErrorMessage = (code) =>
  RESTORE_ERROR_COPY[code] ||
  _("Unable to restore the previous configuration.");

const SHARE_ERROR_COPY = {
  invalid_name: _("Please enter a name."),
  invalid_description: _("That description is too long."),
  nickname_taken: _("That name is already taken. Try another."),
  invalid_nickname: _("Pick a name between 1 and 40 characters."),
  config_unavailable: _("Your current configuration can't be shared right now."),
  payload_build_failed: _("Your current configuration can't be shared right now."),
  hub_unreachable: _("Couldn't reach the theme store. Please try again."),
};

const shareErrorMessage = (code) =>
  SHARE_ERROR_COPY[code] || _("Unable to share this configuration right now.");

const nicknameErrorMessage = (code) =>
  SHARE_ERROR_COPY[code] || _("Couldn't save that name. Try again.");

const UPDATE_ERROR_COPY = {
  invalid_id: _("This share is no longer available."),
  config_unavailable: _("Your current configuration can't be shared right now."),
  payload_build_failed: _("Your current configuration can't be shared right now."),
  hub_unreachable: _("Couldn't reach the theme store. Please try again."),
};

const updateErrorMessage = (code) =>
  UPDATE_ERROR_COPY[code] || _("Unable to update this share right now.");

const DELETE_ERROR_COPY = {
  invalid_id: _("This share is no longer available."),
  hub_unreachable: _("Couldn't reach the theme store. Please try again."),
};

const deleteErrorMessage = (code) =>
  DELETE_ERROR_COPY[code] || _("Unable to delete this share right now.");

const buildConfirmActions = (onConfirm, confirmLabel) =>
  E("div", { class: "right", style: "margin-top:1em;" }, [
    E("button", { class: "btn", click: ui.hideModal }, _("Cancel")),
    " ",
    E(
      "button",
      { class: "btn cbi-button-action important", click: onConfirm },
      confirmLabel,
    ),
  ]);

const buildSimpleApplyConfirm = (onConfirm) => [
  E(
    "p",
    {},
    _(
      "Apply this configuration now? Your current settings are backed up first.",
    ),
  ),
  buildConfirmActions(onConfirm, _("Apply")),
];

const buildExternalUrlConfirm = (urls, onConfirm) => [
  E("p", {}, _("This configuration links to these external sites:")),
  E(
    "ul",
    { style: "margin:0.25em 0 0.75em;padding-left:1.2em;word-break:break-all;" },
    urls.map((url) => E("li", {}, [document.createTextNode(url)])),
  ),
  E(
    "p",
    {},
    _("Apply it anyway? Your current settings are backed up first."),
  ),
  buildConfirmActions(onConfirm, _("Apply")),
];

// ---------------------------------------------------------------------------
// Injected stylesheet: self-contained so the page degrades acceptably under
// non-Aurora themes (every var() carries a fallback). Static string only.

const STORE_CSS =
  ".aurora-store-head{display:flex;gap:0.8em;align-items:flex-end;flex-wrap:wrap;" +
  "margin:0.4em 0 0;}" +
  ".aurora-store-head h2{margin:0;}" +
  ".aurora-store-head input{max-width:280px;}" +
  ".aurora-store-head .sp{flex:1;}" +
  ".aurora-store-applied{display:flex;align-items:center;gap:0.6em;flex-wrap:wrap;" +
  "margin-top:0.9em;padding:0.35em 0.4em 0.35em 0.9em;border-radius:0.6em;" +
  "background:var(--brand-subtle,rgba(0,134,191,0.12));font-size:0.9em;}" +
  ".aurora-store-applied .sp{flex:1;}" +
  ".aurora-store-tick{color:var(--brand,#0086bf);font-size:0.85em;}" +
  ".aurora-store-filters{display:flex;gap:2px;flex-wrap:wrap;margin-top:0.9em;" +
  "padding:3px;width:max-content;max-width:100%;border-radius:10px;" +
  "background:var(--surface-sunken,rgba(0,0,0,0.04));" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.1));}" +
  ".aurora-store-filters button{border:0;background:transparent;font:inherit;" +
  "font-size:0.88em;color:var(--text-muted,#666);padding:0.35em 0.85em;" +
  "border-radius:7px;cursor:pointer;white-space:nowrap;}" +
  ".aurora-store-filters button:hover{color:var(--text,#111);}" +
  ".aurora-store-filters button.active{background:var(--surface,#fff);" +
  "color:var(--text,#111);font-weight:600;" +
  "box-shadow:var(--app-shadow-sm,0 1px 2px rgba(0,0,0,0.08));}" +
  ".aurora-store-filters .n{font-size:0.8em;opacity:0.6;margin-left:0.4em;}" +
  ".aurora-store-section-title{display:flex;align-items:baseline;gap:0.6em;" +
  "margin:1.6em 0 0.6em;}" +
  ".aurora-store-section-title h3{margin:0;font-size:0.95em;font-weight:650;}" +
  ".aurora-store-section-title span{font-size:0.8em;color:var(--text-subtle,#888);}" +
  // min(252px,100%) rather than a bare 252px: auto-fill still lays a 252px
  // track when the container is narrower than that, and the grid then runs off
  // the side of a small phone. The min() clamps the track to whatever room
  // there actually is.
  ".aurora-store-grid{display:grid;" +
  "grid-template-columns:repeat(auto-fill,minmax(min(252px,100%),1fr));" +
  "gap:16px;margin-top:0.4em;}" +
  ".aurora-store-card{background:var(--surface,#fff);border:1px solid var(--hairline,rgba(0,0,0,0.12));" +
  "border-radius:13px;overflow:hidden;cursor:pointer;transition:transform .15s,box-shadow .15s,border-color .15s;}" +
  ".aurora-store-card:hover{transform:translateY(-3px);box-shadow:0 2px 6px rgba(0,0,0,0.12)," +
  "0 10px 28px rgba(0,0,0,0.10);border-color:color-mix(in srgb,var(--brand,#0086bf) 40%," +
  "var(--hairline,rgba(0,0,0,0.12)));}" +
  ".aurora-store-prev{aspect-ratio:16/10;position:relative;" +
  "border-bottom:1px solid var(--hairline,rgba(0,0,0,0.08));}" +
  ".aurora-store-dots{position:absolute;right:8px;bottom:8px;z-index:2;display:flex;" +
  "padding:4px 6px;border-radius:999px;background:var(--surface,#fff);" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.12));}" +
  ".aurora-store-acts{position:absolute;left:8px;bottom:8px;opacity:0;transition:opacity .15s;z-index:2;}" +
  ".aurora-store-card:hover .aurora-store-acts{opacity:1;}" +
  ".aurora-store-meta{padding:10px 12px 11px;}" +
  ".aurora-store-nm{font-weight:600;display:flex;align-items:center;gap:6px;word-break:break-word;}" +
  ".aurora-store-glyphs{margin-left:auto;display:flex;gap:3px;flex:none;}" +
  ".aurora-store-glyphs span{width:19px;height:19px;display:grid;place-items:center;" +
  "border-radius:5px;background:var(--surface-sunken,rgba(0,0,0,0.04));" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.08));font-size:0.62em;" +
  "line-height:1;color:var(--text-muted,#777);}" +
  ".aurora-store-ft{display:flex;align-items:center;gap:6px;margin-top:5px;font-size:0.8em;" +
  "color:var(--text-muted,#777);}" +
  ".aurora-store-ft .dl{margin-left:auto;white-space:nowrap;}" +
  ".aurora-store-badge{display:inline-flex;font-size:0.72em;font-weight:600;padding:1px 8px;" +
  "border-radius:999px;background:var(--surface-sunken,rgba(0,0,0,0.05));color:var(--text-muted,#666);" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.1));}" +
  ".aurora-store-badge.builtin{background:var(--brand-subtle,rgba(0,134,191,0.12));" +
  "color:var(--brand,#0086bf);border-color:transparent;}" +
  ".aurora-store-card.current{border-color:var(--brand,#0086bf);}" +
  ".aurora-store-pin{position:absolute;left:9px;top:9px;z-index:3;width:20px;height:20px;" +
  "border-radius:50%;display:grid;place-items:center;background:var(--brand,#0086bf);" +
  "color:var(--on-brand,#fff);font-size:0.7em;line-height:1;" +
  "box-shadow:0 0 0 2px var(--surface,#fff);}" +
  ".aurora-store-mask{position:fixed;inset:0;background:rgba(0,0,0,0.4);opacity:0;" +
  "pointer-events:none;transition:opacity .2s;z-index:1090;}" +
  ".aurora-store-drawer{position:fixed;top:0;right:-480px;width:460px;max-width:92vw;bottom:0;" +
  "z-index:1091;background:var(--surface,#fff);border-left:1px solid var(--hairline,rgba(0,0,0,0.12));" +
  "transition:right .22s ease;display:flex;flex-direction:column;}" +
  ".aurora-store-open .aurora-store-mask{opacity:1;pointer-events:auto;}" +
  ".aurora-store-open .aurora-store-drawer{right:0;}" +
  ".aurora-store-panes{display:grid;grid-template-columns:1fr 1fr;gap:10px;" +
  "padding:1em 1.3em 0;flex:none;}" +
  ".aurora-store-pane{margin:0;}" +
  ".aurora-store-pane-box{position:relative;aspect-ratio:16/10;border-radius:8px;" +
  "overflow:hidden;border:1px solid var(--hairline,rgba(0,0,0,0.12));}" +
  ".aurora-store-pane figcaption{font-size:0.75em;color:var(--text-muted,#777);" +
  "text-align:center;margin-top:5px;}" +
  ".aurora-store-drawer-body{padding:1em 1.3em;overflow:auto;flex:1;}" +
  ".aurora-store-dt-title{margin:0 0 0.25em;word-break:break-word;}" +
  ".aurora-store-dt-sub{color:var(--text-muted,#777);font-size:0.85em;}" +
  ".aurora-store-dt-desc{color:var(--text-muted,#777);font-size:0.9em;" +
  "word-break:break-word;margin:0.8em 0 0;}" +
  ".aurora-store-dt-h{margin:1.4em 0 0.6em;font-size:0.72em;font-weight:700;" +
  "letter-spacing:0.09em;text-transform:uppercase;color:var(--text-subtle,#888);}" +
  ".aurora-store-kv{display:grid;grid-template-columns:auto 1fr;gap:5px 18px;" +
  "margin:0;font-size:0.88em;}" +
  ".aurora-store-kv dt{color:var(--text-muted,#777);white-space:nowrap;}" +
  ".aurora-store-kv dd{margin:0;text-align:right;word-break:break-word;}" +
  ".aurora-store-pal{display:grid;gap:6px;}" +
  ".aurora-store-pal-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap;}" +
  ".aurora-store-pal-row .l{font-size:0.72em;color:var(--text-subtle,#888);" +
  "width:2.6em;flex:none;}" +
  ".aurora-store-dt-foot{color:var(--text-muted,#777);font-size:0.8em;margin-top:1.4em;}" +
  ".aurora-store-drawer-foot{flex:none;padding:0.9em 1.3em;display:flex;gap:0.6em;" +
  "border-top:1px solid var(--hairline,rgba(0,0,0,0.1));}" +
  ".aurora-store-drawer-foot .apply{flex:1;}" +
  ".aurora-store-drawer-foot .apply[disabled]{opacity:0.45;cursor:default;}" +
  ".aurora-store-tiles{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px;}" +
  ".aurora-store-tile{display:inline-flex;align-items:center;gap:5px;font-size:0.75em;" +
  "color:var(--text-muted,#777);background:var(--surface-sunken,rgba(0,0,0,0.04));" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.08));border-radius:7px;" +
  "padding:2px 8px 2px 3px;white-space:nowrap;max-width:100%;}" +
  ".aurora-store-tile>span:last-child{min-width:0;overflow:hidden;" +
  "text-overflow:ellipsis;}" +
  ".aurora-store-tile .g{flex:none;display:grid;place-items:center;width:20px;height:20px;" +
  "border-radius:5px;background:var(--surface,#fff);color:var(--text,#111);" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.08));font-size:0.9em;line-height:1;}" +
  ".aurora-store-sc{list-style:none;margin:0;padding:0;display:grid;gap:1px;" +
  "border-radius:10px;overflow:hidden;border:1px solid var(--hairline,rgba(0,0,0,0.1));}" +
  ".aurora-store-sc li{display:flex;align-items:center;gap:10px;padding:8px 10px;" +
  "background:var(--surface-sunken,rgba(0,0,0,0.04));font-size:0.85em;}" +
  ".aurora-store-sc li.off{opacity:0.45;}" +
  ".aurora-store-sc .ic{width:24px;height:24px;flex:none;display:grid;place-items:center;" +
  "border-radius:6px;background:var(--surface,#fff);color:var(--text-muted,#777);" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.08));font-size:0.8em;line-height:1;}" +
  ".aurora-store-sc .nm{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;" +
  "white-space:nowrap;}" +
  ".aurora-store-sc .to{font-size:0.85em;color:var(--text-subtle,#888);" +
  "font-family:ui-monospace,Menlo,monospace;overflow:hidden;text-overflow:ellipsis;" +
  "white-space:nowrap;max-width:44%;}" +
  ".aurora-store-sc .ext{flex:none;color:var(--text-muted,#777);font-size:0.85em;}" +
  ".aurora-store-sc-note{color:var(--text-subtle,#888);font-size:0.78em;" +
  "margin:0.5em 0 0;line-height:1.6;}" +
  ".aurora-store-share{background:var(--surface,#fff);border:1px solid var(--hairline,rgba(0,0,0,0.12));" +
  "border-radius:12px;padding:1em 1.3em 1.3em;margin-top:1em;}" +
  ".aurora-store-share-head{display:flex;align-items:center;justify-content:space-between;" +
  "gap:1em;margin-bottom:1em;}" +
  ".aurora-store-share-cols{display:grid;grid-template-columns:240px 1fr;gap:1.6em;}" +
  "@media (max-width:700px){.aurora-store-share-cols{grid-template-columns:1fr;}}" +
  ".aurora-store-share-prev .aurora-store-prev{border:1px solid var(--hairline,rgba(0,0,0,0.12));" +
  "border-radius:10px;overflow:hidden;}" +
  ".aurora-store-field{margin-bottom:0.9em;}" +
  ".aurora-store-field label{display:block;font-size:0.8em;font-weight:600;" +
  "color:var(--text-muted,#666);margin-bottom:4px;}" +
  ".aurora-store-field input,.aurora-store-field textarea{width:100%;}" +
  ".aurora-store-keybar{display:flex;justify-content:space-between;align-items:center;" +
  "gap:1em;flex-wrap:wrap;padding:0.8em 1em;margin:0.8em 0;" +
  "border:1px solid var(--hairline,rgba(0,0,0,0.12));border-radius:10px;}" +
  // A card's quick-apply button is revealed by hovering the card. A touch
  // screen never hovers, so on a phone that button was simply unreachable --
  // the only way to apply from the grid was to open the drawer first. Keyed on
  // the pointer, not the width: a narrow desktop window still has a mouse.
  "@media (hover:none){.aurora-store-acts{opacity:1;}}" +
  // Without this a flick that runs past the end of the drawer's own scroll
  // keeps going in the page underneath, which then sits at a different offset
  // when the drawer closes.
  ".aurora-store-drawer-body{overscroll-behavior:contain;}" +
  "@media (max-width:600px){" +
  // Both spacers exist to push a button to the right edge of a wide row.
  // Once the row wraps they only add a blank line.
  ".aurora-store-head .sp,.aurora-store-applied .sp{display:none;}" +
  ".aurora-store-head input{flex:1 1 100%;max-width:none;}" +
  ".aurora-store-head .cbi-button-add{flex:1 1 100%;}" +
  // Five tabs do not fit on a phone. Scrolling them sideways is what
  // LuCI's own .cbi-tabmenu does; wrapping turns a one-line segmented
  // control into a two-row block that reads like two separate groups.
  // width:max-content from the base rule still hugs the pills when they do
  // fit -- max-width:100% is what makes the overflow scroll instead.
  ".aurora-store-filters{flex-wrap:nowrap;overflow-x:auto;" +
  "scrollbar-width:none;-ms-overflow-style:none;}" +
  ".aurora-store-filters::-webkit-scrollbar{display:none;}" +
  // Basis 100%: the sentence takes the whole first line and the Restore
  // button drops below it, rather than the two sharing a line that fits
  // neither -- the button alone is wider than a 320px screen's text column.
  ".aurora-store-applied .msg{flex:1 1 100%;}" +
  ".aurora-store-keybar{align-items:flex-start;padding:0.7em 0.8em;}" +
  ".aurora-store-share{padding:0.9em 1em 1em;}" +
  ".aurora-store-grid{gap:12px;}" +
  // The drawer is 92vw here, so its 1.3em gutters cost real reading width.
  ".aurora-store-panes{padding:0.8em 1em 0;gap:8px;}" +
  ".aurora-store-drawer-body{padding:0.9em 1em;}" +
  ".aurora-store-drawer-foot{padding:0.8em 1em;}" +
  // Still two columns -- the labels are short and stacking would double the
  // table's height -- but the 18px gutter is room the values need here.
  ".aurora-store-kv{gap:5px 10px;}" +
  // 44% of a 300px drawer ellipsised most targets down to nothing, so a
  // shortcut becomes two lines here: glyph + title + the ↗ marker, then the
  // target underneath, indented to line up with the title. `order` is what
  // keeps ↗ next to the title it marks -- it sits after the target in the
  // DOM, and without it the marker gets pushed onto a third line of its own.
  ".aurora-store-sc li{flex-wrap:wrap;gap:4px 10px;}" +
  ".aurora-store-sc .nm{flex:1 1 auto;}" +
  ".aurora-store-sc .to{order:1;flex:1 1 100%;max-width:100%;" +
  "padding-left:34px;}" +
  "}";

return view.extend({
  handleSave: null,
  handleSaveApply: null,
  handleReset: null,

  load() {
    // 刻意只留本地来源。presets.json 随包安装,uci.load 走本机 ubus(实测
    // ~90ms)。到 hub 的两个调用移到 render() 之后 —— LuCI 在 load() resolve
    // 前不会进 render(),把一次 205ms RTT / 首连 800ms 的往返放在这里,等于
    // 让首屏白等它。
    return Promise.all([
      L.resolveDefault(
        fetch(L.resource("aurora/presets.json")).then((res) =>
          res.ok ? res.json() : null,
        ),
        null,
      ),
      uci.load("aurora"),
    ]).then(([presetsRes]) => ({
      presets: (presetsRes && presetsRes.presets) || null,
      hubApplied: uci.get("aurora", "theme", "hub_applied") || "",
      // Set by rpcd whenever the key leaves the router (export or import).
      // Lives in uci rather than localStorage so it follows a keep-settings
      // upgrade, survives a browser change, and resets to zero on the clean
      // reflash that is exactly when the reminder should come back.
      keySaved: uci.get("aurora", "theme", "hub_key_saved") === "1",
      activePreset: uci.get("aurora", "theme", "active_preset") || "default",
      // This router's own navigation shape. It used to stand in for the
      // built-in presets' too, back when a preset changed only colours; now
      // every preview draws the configuration's own nav_type and this is read
      // by the publish panel alone -- the preview and manifest of what YOUR
      // configuration would look like in the store.
      navType: uci.get("aurora", "theme", "nav_type") || "mega-menu",
    }));
  },

  render(loadData) {
    let appliedName = loadData.hubApplied || "";
    const activePreset =
      loadData.activePreset === "classic" || !loadData.activePreset
        ? "default"
        : loadData.activePreset;
    const currentNav = loadData.navType;

    // Built-in preset card models: local data, offline-safe. When presets.json
    // is missing (broken install) the group renders nothing.
    //
    // `preview` is the projection a hub list row carries (colors / layout /
    // typography / toolbar), written by scripts/gen-presets.mjs from the same
    // templates rpcd applies. That is the whole point of the shape: paletteOf,
    // navOf and tileEntriesFor then read a built-in preset with the accessors
    // they already use for a shared configuration, so the two card kinds
    // cannot describe a look differently.
    const builtinItems = loadData.presets
      ? BUILTIN_PRESETS.filter((preset) => loadData.presets[preset.id]).map(
          (preset) => ({
            id: preset.id,
            label: preset.label,
            preview: loadData.presets[preset.id],
          }),
        )
      : [];

    const state = {
      tab: "all",
      query: "",
      online: { hot: null, new: null },
      onlineFailed: false,
      showingStale: false,
    };

    const styleEl = E("style", { type: "text/css" });
    styleEl.textContent = STORE_CSS;

    const rootEl = E("div", { class: "cbi-map aurora-store" });
    const bannerEl = E("div", { id: "aurora-hub-banner" });
    const contentEl = E("div", {});
    const drawerMask = E("div", { class: "aurora-store-mask" });
    const drawerEl = E("div", { class: "aurora-store-drawer" });

    const closeDrawer = () => rootEl.classList.remove("aurora-store-open");
    drawerMask.addEventListener("click", closeDrawer);

    // ------------------------------------------------------------------
    // Rollback banner

    const confirmRestore = () => {
      ui.showModal(_("Restore Previous Configuration"), [
        E(
          "p",
          {},
          _(
            "This replaces your current settings with the ones from just before the last applied configuration.",
          ),
        ),
        buildConfirmActions(() => {
          ui.showModal(_("Restoring"), [
            E("p", { class: "spinning" }, _("Restoring…")),
          ]);
          L.resolveDefault(hubApi.callHubRestore(), null).then((res) => {
            if (res && res.result === 0) {
              window.location.reload();
              return;
            }
            ui.hideModal();
            ui.addNotification(
              null,
              E("p", {}, restoreErrorMessage(res && res.error)),
              "warning",
            );
          });
        }, _("Restore")),
      ]);
    };

    const renderBanner = () => {
      while (bannerEl.firstChild) bannerEl.removeChild(bannerEl.firstChild);
      if (!appliedName) {
        bannerEl.className = "";
        return;
      }
      bannerEl.className = "aurora-store-applied";
      // Tick and sentence are one flex item, not two. As siblings the tick was
      // a flex item in its own right, so on a narrow screen the sentence wrapped
      // to the next line and left a lone ✓ sitting above it.
      bannerEl.appendChild(
        E("span", { class: "msg" }, [
          buildCurrentTick(),
          document.createTextNode(" " + _("In use") + " "),
          E("strong", {}, [document.createTextNode(appliedName)]),
        ]),
      );
      bannerEl.appendChild(E("span", { class: "sp" }));
      bannerEl.appendChild(
        E(
          "button",
          { type: "button", class: "cbi-button", click: confirmRestore },
          _("Restore previous configuration"),
        ),
      );
    };

    // ------------------------------------------------------------------
    // Online apply flow (backup -> job -> poll -> banner)

    const pollApplyStatus = (jobId, remaining, name) => {
      if (remaining <= 0) {
        ui.hideModal();
        ui.addNotification(
          null,
          E("p", {}, _("Applying timed out. Please try again.")),
          "warning",
        );
        return;
      }

      window.setTimeout(() => {
        L.resolveDefault(hubApi.callGetHubStatus(jobId), {}).then((status) => {
          if (status && status.state === "done") {
            ui.hideModal();
            appliedName = name;
            renderBanner();
            ui.addNotification(null, E("p", {}, _("Applied.")), "info");
          } else if (status && status.state === "error") {
            ui.hideModal();
            ui.addNotification(
              null,
              E("p", {}, applyErrorMessage(status.error)),
              "warning",
            );
          } else {
            pollApplyStatus(jobId, remaining - 1, name);
          }
        });
      }, 1500);
    };

    const startApply = (id, name) => {
      ui.showModal(_("Applying"), [
        E("p", { class: "spinning" }, _("Applying this configuration…")),
      ]);
      L.resolveDefault(hubApi.callHubApply(id), null).then((res) => {
        if (!res || res.result !== 0 || !res.job_id) {
          ui.hideModal();
          ui.addNotification(
            null,
            E("p", {}, applyErrorMessage(res && res.error)),
            "warning",
          );
          return;
        }
        pollApplyStatus(res.job_id, 20, name);
      });
    };

    const confirmOnlineApply = (item) => {
      closeDrawer();
      const urls = externalToolbarUrls(item.payload || {});
      const onConfirm = () => startApply(item.id, item.name);
      ui.showModal(
        _("Apply Configuration"),
        urls.length
          ? buildExternalUrlConfirm(urls, onConfirm)
          : buildSimpleApplyConfirm(onConfirm),
      );
    };

    // Quick apply from a card: the external-URL callout needs the full
    // payload, so fetch the detail first, then reuse the drawer's confirm.
    const quickApplyOnline = (id) => {
      ui.showModal(_("Applying"), [
        E("p", { class: "spinning" }, _("Loading theme details…")),
      ]);
      L.resolveDefault(hubApi.callHubGet(id), null).then((res) => {
        ui.hideModal();
        if (!res || res.result !== 0 || !res.data) {
          ui.addNotification(
            null,
            E("p", {}, applyErrorMessage(res && res.error)),
            "warning",
          );
          return;
        }
        confirmOnlineApply(res.data);
      });
    };

    // ------------------------------------------------------------------
    // Built-in preset apply: local rpcd path, identical semantics (and
    // msgids) to the old preset dropdown -- colors only, immediate, reload.

    const confirmBuiltinApply = (preset) => {
      closeDrawer();
      ui.showModal(_("Apply Preset"), [
        E(
          "p",
          {},
          _(
            "Apply the '%s' preset now? It is saved immediately and the page reloads. A preset carries a whole look — colors, navigation, spacing, corner radius, content width and fonts. Your shortcuts, logo, icons and login background are left as they are.",
          ).format(preset.label),
        ),
        buildConfirmActions(() => {
          ui.showModal(_("Applying..."), [
            E("p", { class: "spinning" }, _("Applying preset...")),
          ]);
          L.resolveDefault(callApplyThemePreset(preset.id), {}).then((ret) => {
            ui.hideModal();
            if (ret && ret.result === 0) {
              ui.addNotification(
                null,
                E("p", _("Preset applied successfully.")),
                "info",
              );
              window.location.reload();
            } else {
              ui.addNotification(
                null,
                E("p", _("Apply failed: %s").format((ret && ret.error) || "Unknown")),
                "error",
              );
            }
          });
        }, _("Apply")),
      ]);
    };

    // ------------------------------------------------------------------
    // Detail drawer

    const renderDrawer = (children) => {
      while (drawerEl.firstChild) drawerEl.removeChild(drawerEl.firstChild);
      children.forEach((child) => drawerEl.appendChild(child));
      rootEl.classList.add("aurora-store-open");
    };

    const drawerFoot = (applyLabel, onApply, current) =>
      E("div", { class: "aurora-store-drawer-foot" }, [
        E("button", { type: "button", class: "btn", click: closeDrawer }, _("Close")),
        current
          ? E(
              "button",
              { type: "button", class: "btn apply", disabled: "disabled" },
              "✓ " + _("In use"),
            )
          : E(
              "button",
              {
                type: "button",
                class: "btn cbi-button-action important apply",
                click: onApply,
              },
              applyLabel,
            ),
      ]);

    const openBuiltinDrawer = (preset) => {
      const current = preset.id === activePreset;
      const typography = preset.preview.typography || {};
      const title = E("h3", { style: "margin:0 0 0.3em;" }, [
        document.createTextNode(preset.label),
        " ",
        E("span", { class: "aurora-store-badge builtin" }, _("Built-in")),
      ]);
      if (current) title.appendChild(buildCurrentTick());

      const body = [
        title,
        E(
          "p",
          { class: "aurora-store-dt-desc" },
          _("Ships with the theme and works offline."),
        ),
        buildDetailHeading(_("Colors")),
        buildPaletteChips(preset),
        buildDetailHeading(_("Layout & Typography")),
        buildLayoutRows(preset.preview.layout || {}, typography),
      ];

      if (needsFontDownload(typography))
        body.push(
          E(
            "p",
            { class: "aurora-store-sc-note" },
            _(
              "This preset uses a downloaded typeface. The router fetches it once after applying; until then the text falls back to the built-in font.",
            ),
          ),
        );

      body.push(
        E(
          "p",
          { class: "aurora-store-dt-foot" },
          _(
            "Your shortcuts, logo, icons and login background are left exactly as they are.",
          ),
        ),
      );

      renderDrawer([
        buildPanes(paletteOf(preset), previewOpts(preset)),
        E("div", { class: "aurora-store-drawer-body" }, body),
        drawerFoot(_("Apply"), () => confirmBuiltinApply(preset), current),
      ]);
    };

    const renderDrawerLoadError = () => {
      if (!rootEl.classList.contains("aurora-store-open")) return;
      renderDrawer([
        E("div", { class: "aurora-store-drawer-body" }, [
          E("p", {}, _("Unable to load this theme right now. Please try again.")),
        ]),
        E("div", { class: "aurora-store-drawer-foot" }, [
          E("button", { type: "button", class: "btn", click: closeDrawer }, _("Close")),
        ]),
      ]);
    };

    const openOnlineDrawer = (id) => {
      renderDrawer([
        E("div", { class: "aurora-store-drawer-body" }, [
          E("p", { class: "spinning" }, _("Loading theme details…")),
        ]),
      ]);
      L.resolveDefault(hubApi.callHubGet(id), null)
        .then((res) => {
          if (!rootEl.classList.contains("aurora-store-open")) return;
          if (!res || res.result !== 0 || !res.data) {
            renderDrawerLoadError();
            return;
          }
          const item = res.data;
          renderDrawer([
            buildPanes(paletteOf(item), previewOpts(item)),
            E("div", { class: "aurora-store-drawer-body" }, [buildDetailBody(item)]),
            drawerFoot(_("Apply"), () => confirmOnlineApply(item)),
          ]);
        })
        .catch(renderDrawerLoadError);
    };

    // ------------------------------------------------------------------
    // Cards

    const buildBadge = (label, extraClass) =>
      E("span", { class: "aurora-store-badge " + (extraClass || "") }, label);

    // 内置卡和社区卡画的是同一个东西,只是数据来源不同。两个各自为政的构造器
    // 已经漂移过一次 —— 社区卡长出了徽章而内置卡没有 —— 所以只留一个。
    const buildCard = (model) => {
      const prev = E("div", { class: "aurora-store-prev" }, [
        buildDuo(model.palette, model.opts),
        E("span", { class: "aurora-store-dots" }, [buildDotRow(model.palette)]),
        E("div", { class: "aurora-store-acts" }, [
          E(
            "button",
            {
              type: "button",
              class: "btn cbi-button-action",
              click: (ev) => {
                ev.stopPropagation();
                model.apply();
              },
            },
            model.current ? _("Re-apply") : _("Apply"),
          ),
        ]),
      ]);
      if (model.current) prev.appendChild(buildCurrentPin());

      const nm = E("div", { class: "aurora-store-nm" }, [
        document.createTextNode(model.name),
      ]);
      if (model.badge) nm.appendChild(model.badge);
      if (model.glyphs) nm.appendChild(model.glyphs);

      return E(
        "div",
        {
          class: "aurora-store-card" + (model.current ? " current" : ""),
          click: model.open,
        },
        [
          prev,
          E("div", { class: "aurora-store-meta" }, [
            nm,
            E("div", { class: "aurora-store-ft" }, [
              E("span", { style: "word-break:break-all;" }, [
                document.createTextNode(model.author),
              ]),
              E("span", { class: "dl" }, [document.createTextNode(model.right)]),
            ]),
          ]),
        ],
      );
    };

    // 内置卡不带 "Built-in" 徽章:它上方的分区标题已经写着"内置",而每张卡
    // 再重复一遍就是拿掉一行密度换零信息。徽章那个样式类留着,抽屉还在用。
    //
    // 缩略图画的是预设自己的导航形态,glyph 行出的是它自己的字体和圆角 ——
    // 内置预设现在带的是一整套外观,而不是一组色值,卡片必须让人在点进去之前
    // 就看得出这一点。
    const buildBuiltinCard = (preset) => buildCard({
      name: preset.label,
      author: "Aurora",
      right: _("Works offline"),
      palette: paletteOf(preset),
      opts: previewOpts(preset),
      badge: null,
      glyphs: buildCardGlyphs(preset),
      current: preset.id === activePreset,
      open: () => openBuiltinDrawer(preset),
      apply: () => confirmBuiltinApply(preset),
    });

    const buildOnlineCard = (item) => buildCard({
      name: item.name || _("Untitled theme"),
      author: item.author || _("Anonymous"),
      right: formatDownloads(item.downloads),
      palette: paletteOf(item),
      opts: previewOpts(item),
      badge:
        item.assets_status && item.assets_status !== "none"
          ? buildBadge(_("Includes assets"))
          : null,
      glyphs: buildCardGlyphs(item),
      current: false,
      open: () => openOnlineDrawer(item.id),
      apply: () => quickApplyOnline(item.id),
    });

    // ------------------------------------------------------------------
    // My shares

    const mySharesEl = E("div", { id: "aurora-hub-my-shares" });

    // One request carries both halves of the answer: who this router
    // publishes as, and what it has published.
    // hub_me 是本页唯一还走 ubus 的网络调用 —— device_token 是 0600 的写凭证
    // (hub_share/hub_update/hub_delete 都靠它认证),不下发到浏览器。整条链路
    // 实测约 0.9s,其中 ubus 只占 0.09s,其余全是路由器到 hub 那次不可复用的
    // TLS 握手加 205ms 跨太平洋 RTT。所以结果要落缓存:下次打开页面由缓存先
    // 画,这一次往返就不再挡在首屏前面。
    //
    // 失败时刻意什么都不做。原先是 applyMe(null),而 applyMe 会把 myShares
    // 置空 —— 断网的用户会眼看着自己已发布的作品从界面上消失。保留上一帧才
    // 是诚实的:我们只是没拿到新数据,不是作品没了。
    const refreshMyShares = () =>
      L.resolveDefault(hubApi.callHubMe(), null).then((res) => {
        if (res && res.result === 0) {
          hubApi.meCache.set(res.data);
          applyMe(res.data);
        }
      });

    const applyMe = (data) => {
      profile = {
        id: (data && data.id) || null,
        nickname: (data && data.nickname) || null,
      };
      renderMyShares((data && data.configs) || []);
    };

    // An update rebuilds and re-sends the whole configuration -- logo, login
    // background, site and app icons, shortcuts included -- so it shows the
    // same manifest the publish panel does instead of a bare one-liner.
    const confirmUpdateShare = (item) => {
      ui.showModal(_("Update Share"), [
        E(
          "p",
          {},
          _(
            "Replace the shared configuration with your current settings?",
          ),
        ),
        E("h4", { style: "margin:1.2em 0 0.4em;" }, _("What gets shared")),
        buildManifestTable(),
        E(
          "p",
          { style: "color:var(--text-muted);font-size:0.8em;margin-top:0.8em;" },
          _("Anyone who applies this gets all of it. You can update or remove it later."),
        ),
        buildConfirmActions(() => {
          ui.showModal(_("Updating"), [
            E("p", { class: "spinning" }, _("Updating…")),
          ]);
          L.resolveDefault(
            hubApi.callHubUpdate(item.id, item.name, item.description || ""),
            null,
          ).then((res) => {
            ui.hideModal();
            if (res && res.result === 0) {
              ui.addNotification(null, E("p", {}, _("Updated.")), "info");
              refreshMyShares();
            } else {
              ui.addNotification(
                null,
                E("p", {}, updateErrorMessage(res && res.error)),
                "warning",
              );
            }
          });
        }, _("Update")),
      ]);
    };

    const confirmDeleteShare = (item) => {
      // Static message, deliberately not interpolating item.name: asset-upload's
      // confirmDelete renders opts.message as a bare E() child, which LuCI can
      // route through innerHTML, and the hub config name is attacker-controlled
      // free text (the hub only strips control characters).
      assetUpload
        .confirmDelete({
          title: _("Delete Share"),
          message: _("Delete this shared configuration from the theme store?"),
        })
        .then((confirmed) => {
          if (!confirmed) return;
          return L.resolveDefault(hubApi.callHubDelete(item.id), null).then(
            (res) => {
              if (res && res.result === 0) {
                ui.addNotification(null, E("p", {}, _("Deleted.")), "info");
                refreshMyShares();
              } else {
                ui.addNotification(
                  null,
                  E("p", {}, deleteErrorMessage(res && res.error)),
                  "warning",
                );
              }
            },
          );
        });
    };

    const buildMyShareRow = (item) => {
      const updateBtn = E(
        "button",
        {
          type: "button",
          class: "cbi-button",
          click: () => confirmUpdateShare(item),
        },
        _("Update with current configuration"),
      );
      const deleteBtn = E(
        "button",
        {
          type: "button",
          class: "cbi-button cbi-button-remove",
          click: () => confirmDeleteShare(item),
        },
        _("Delete"),
      );

      // The action cell is `td.cbi-section-actions` wrapping a single <div>,
      // which is the shape LuCI's own TableSection emits. Under the mobile
      // breakpoint every theme gives that cell the whole row width and lets
      // the buttons inside it wrap. It used to be `td center` with
      // white-space:nowrap, which pinned "Update with current configuration"
      // and "Delete" onto one unbreakable line: on a 390px phone the row ran
      // to 748px and Delete sat off the right edge of the screen.
      //
      // Deliberately no data-title on the two data cells. Themes hide
      // `.tr.table-titles` on a phone and reprint the column name from that
      // attribute, which is worth it when a bare cell would be ambiguous --
      // here "Nord Midnight" and "128 downloads" already say what they are,
      // and a "Name"/"Downloads" line above each would only stutter.
      return E("tr", { class: "tr" }, [
        E("td", { class: "td", style: "word-break:break-word;" }, [
          document.createTextNode(item.name || _("Untitled theme")),
        ]),
        E("td", { class: "td", style: "color:var(--text-muted);" }, [
          document.createTextNode(formatDownloads(item.downloads)),
        ]),
        E("td", { class: "td cbi-section-actions" }, [
          E("div", {}, [updateBtn, " ", deleteBtn]),
        ]),
      ]);
    };

    let myShares = [];

    // Whoever this router publishes as. A null nickname means the creator
    // account exists but has never been named.
    let profile = { id: null, nickname: null };

    let keySaved = loadData.keySaved;

    // A Blob and an object URL rather than a data: URI -- the key never
    // becomes part of a URL that could be kept in history.
    const downloadKey = (key) => {
      const blob = new Blob([key + "\n"], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = E("a", { href: url, download: "aurora-creator-key.txt" });
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    };

    const backupKeyPrompt = () => {
      L.resolveDefault(hubApi.callHubExportKey(), null).then((res) => {
        if (!res || res.result !== 0 || !res.key) {
          ui.addNotification(
            null,
            E("p", {}, _("Couldn't read your key. Please try again.")),
            "warning",
          );
          return;
        }

        // rpcd already recorded the flag when it handed the key over; this
        // view is browse-only and has no uci write path of its own.
        keySaved = true;

        const reveal = E(
          "code",
          { style: "word-break:break-all;display:none;margin:0.6em 0;" },
          [document.createTextNode(res.key)],
        );

        ui.showModal(_("Back up your creator key"), [
          E(
            "p",
            {},
            _("This key is your account. Anyone who has it can publish under your name and delete what you have shared."),
          ),
          E(
            "p",
            {},
            _("It exists only on this router. Reflashing without keeping settings erases it."),
          ),
          reveal,
          E("div", { class: "right", style: "margin-top:1em;" }, [
            E(
              "button",
              {
                type: "button",
                class: "cbi-button",
                click: () => {
                  reveal.style.display =
                    reveal.style.display === "none" ? "block" : "none";
                },
              },
              _("Show key"),
            ),
            " ",
            E(
              "button",
              {
                type: "button",
                class: "btn cbi-button-action important",
                click: () => {
                  downloadKey(res.key);
                  ui.hideModal();
                  renderContent();
                },
              },
              _("Download"),
            ),
            " ",
            E(
              "button",
              { type: "button", class: "cbi-button", click: () => ui.hideModal() },
              _("Close"),
            ),
          ]),
        ]);
      });
    };

    // Standing strip above "My Shares": says who this router is, and while
    // the key has never left the box, that losing it is possible.
    const buildKeyBar = () => {
      if (!profile.id) return null;

      const label = profile.nickname
        ? profile.nickname + " · #" + profile.id
        : _("Not named yet") + " · #" + profile.id;

      const actions = [];
      if (!keySaved) {
        actions.push(
          E(
            "button",
            {
              type: "button",
              class: "btn cbi-button-action",
              click: () => backupKeyPrompt(),
            },
            _("Back up key"),
          ),
          " ",
        );
      }
      actions.push(
        E(
          "button",
          { type: "button", class: "cbi-button", click: () => importKeyPrompt() },
          _("Import a key"),
        ),
      );

      return E("div", { class: "aurora-store-keybar" }, [
        E("div", {}, [
          E("strong", {}, [document.createTextNode(label)]),
          E("div", { style: "color:var(--text-muted);font-size:0.85em;" }, [
            document.createTextNode(
              keySaved
                ? _("This account lives on this router.")
                : _("This account exists only on this router — reflashing without keeping settings erases it."),
            ),
          ]),
        ]),
        E("div", {}, actions),
      ]);
    };

    const KEY_RE = /^[a-f0-9]{64}$/;

    const importKeyPrompt = () => {
      // The share panel's fields get their width from .aurora-store-field; this
      // one lives in a modal, where a default-sized textarea leaves a 64-hex
      // key wrapping inside a box narrower than the dialog holding it.
      const input = E("textarea", {
        class: "cbi-input-textarea",
        rows: 2,
        style: "width:100%;box-sizing:border-box;",
      });
      const err = E("p", {
        style: "color:var(--danger);font-weight:600;display:none;margin:0.6em 0 0;",
      });
      const picker = E("input", { type: "file", accept: ".txt,text/plain" });

      // One parse path: the file button only fills the box.
      picker.addEventListener("change", () => {
        const file = picker.files && picker.files[0];
        if (!file) return;
        file.text().then((text) => {
          input.value = text.trim();
        });
      });

      const commit = () => {
        const key = input.value.trim().toLowerCase();
        if (!KEY_RE.test(key)) {
          err.textContent = _("That doesn't look like a creator key.");
          err.style.display = "block";
          return;
        }
        L.resolveDefault(hubApi.callHubImportKey(key), null).then((res) => {
          if (!res || res.result !== 0) {
            err.textContent = _("Couldn't use that key. Check it and try again.");
            err.style.display = "block";
            return;
          }
          ui.hideModal();
          // 换账号了 —— 缓存里那份档案属于上一个 key。先清掉再刷新,否则
          // "导入成功、随后 hub_me 失败"会把上一个账号的作品留在界面上,
          // 而 Task 2 之后失败路径不再自行清空。
          hubApi.meCache.clear();
          applyMe(null);
          refreshMyShares().then(() => {
            keySaved = true;
            ui.addNotification(
              null,
              E(
                "p",
                {},
                myShares.length
                  ? _("Restored. What you shared before is back under this account.")
                  : _("Restored."),
              ),
              "info",
            );
            renderContent();
          });
        });
      };

      const body = [
        E(
          "p",
          {},
          _("Paste the creator key you backed up, or pick the file you downloaded."),
        ),
        input,
        E("div", { style: "margin-top:0.6em;" }, [picker]),
        err,
      ];

      // Replacing a key that still owns published work is unrecoverable, so
      // the current key gets one last chance to be saved first.
      if (myShares.length) {
        body.splice(
          1,
          0,
          E(
            "p",
            { style: "color:var(--danger);" },
            _("This router already has shares of its own. Importing a different key gives them up for good — back up the current key first if you still want them."),
          ),
        );
        body.push(
          E("div", { style: "margin-top:0.8em;" }, [
            E(
              "button",
              { type: "button", class: "cbi-button", click: () => backupKeyPrompt() },
              _("Back up the current key first"),
            ),
          ]),
        );
      }

      body.push(buildConfirmActions(commit, _("Import")));
      ui.showModal(_("Import a creator key"), body);
    };

    // The tab keeps the count of what is already published, so the number is
    // readable without opening the tab first.
    const renderMyShares = (items) => {
      myShares = items || [];
      TABS.forEach(renderTabLabel);
      while (mySharesEl.firstChild) mySharesEl.removeChild(mySharesEl.firstChild);
      if (!myShares.length) {
        mySharesEl.appendChild(
          E(
            "p",
            { style: "color:var(--text-muted);padding:1.5em 0 0.8em;" },
            // Direction-free on purpose: the publish control sits above this
            // message, so "below" pointed at nothing. The second half is what
            // a freshly reflashed router needs -- its work is still in the
            // store, it just needs the key back.
            _("Nothing shared yet — publish your current configuration, or import a creator key to bring back what you shared before."),
          ),
        );
        mySharesEl.appendChild(
          E("div", { style: "padding-bottom:1em;" }, [
            E(
              "button",
              { type: "button", class: "cbi-button", click: () => importKeyPrompt() },
              _("Import a creator key"),
            ),
          ]),
        );
        return;
      }
      mySharesEl.appendChild(
        E("table", { class: "table" }, [
          E("tr", { class: "tr table-titles" }, [
            E("th", { class: "th" }, _("Name")),
            E("th", { class: "th" }, _("Downloads")),
            E("th", { class: "th center" }, ""),
          ]),
          ...myShares.map((item) => buildMyShareRow(item)),
        ]),
      );
    };

    // ------------------------------------------------------------------
    // Publishing: an inline panel inside "My Shares", not a modal, so the
    // manifest of what actually goes out has room to sit next to the fields.

    // Everything the manifest needs is already in uci -- no extra rpc call.
    const shareManifestRows = () => {
      const rows = [
        { label: _("Colors"), detail: _("Light and dark, 62 values") },
        {
          label: _("Navigation"),
          detail: NAV_TYPE_LABELS[currentNav] || currentNav,
        },
      ];

      // build_share_payload sends spacing and content width alongside the
      // navigation shape, and the detail drawer lists both -- leaving them out
      // here would under-promise right above "Anyone who applies this gets all
      // of it."
      const spacing = uci.get("aurora", "theme", "struct_spacing");
      if (spacing) rows.push({ label: _("Spacing"), detail: spacing });

      const radius = radiusLabel(uci.get("aurora", "theme", "struct_radius_base"));
      if (radius) rows.push({ label: _("Shape"), detail: radius });

      const contentWidth = uci.get(
        "aurora",
        "theme",
        "struct_content_width_centered",
      );
      if (contentWidth)
        rows.push({ label: _("Content Width"), detail: contentWidth });

      const family = firstFontFamily(uci.get("aurora", "theme", "struct_font_sans"));
      const mono = firstFontFamily(uci.get("aurora", "theme", "struct_font_mono"));
      if (family)
        rows.push({
          label: _("Fonts"),
          detail: mono ? family + " · " + mono : family,
        });

      // The same five image slots build_share_payload walks, read by name so
      // the keys stay next to the labels they produce. Two slots share the
      // "Site Icon" label and two share "App Icon", so the list is
      // de-duplicated by label -- naming either one twice would be wrong.
      const images = [];
      [
        { name: uci.get("aurora", "theme", "logo_svg"), label: ASSET_LABELS.logo },
        {
          name: uci.get("aurora", "theme", "favicon_png"),
          label: ASSET_LABELS.siteIcon,
        },
        {
          name: uci.get("aurora", "theme", "favicon_ico"),
          label: ASSET_LABELS.siteIcon,
        },
        {
          name: uci.get("aurora", "theme", "pwa_icon_192"),
          label: ASSET_LABELS.appIcon,
        },
        {
          name: uci.get("aurora", "theme", "pwa_icon_512"),
          label: ASSET_LABELS.appIcon,
        },
      ].forEach((slot) => {
        if (isSharedAssetName(slot.name) && images.indexOf(slot.label) === -1)
          images.push(slot.label);
      });
      if (isSharedAssetName(loginBgFilename(uci.get("aurora", "theme", "struct_login_bg"))))
        images.push(ASSET_LABELS.loginBg);
      images.forEach((label) =>
        rows.push({ label: label, detail: _("Included") }),
      );

      // Anonymous toolbar_item sections have no stable index, so the array is
      // filtered and counted rather than iterated by position.
      const shortcuts = Math.min(
        (uci.sections("aurora", "toolbar_item") || []).filter(isSharedToolbarItem)
          .length,
        MAX_SHARED_TOOLBAR_ITEMS,
      );
      if (shortcuts)
        rows.push({
          label: _("Toolbar"),
          detail:
            shortcuts === 1
              ? _("1 shortcut")
              : _("%d shortcuts").format(shortcuts),
        });

      return rows;
    };

    // Shared by the publish panel and the update confirmation: an update runs
    // the very same payload build, so it has to say the same thing about what
    // leaves the router.
    const buildManifestTable = () =>
      E("table", { class: "table" }, [
        E("tr", { class: "tr table-titles" }, [
          E("th", { class: "th" }, _("Content")),
          E("th", { class: "th" }, _("Details")),
        ]),
        // Same call as buildMyShareRow: no data-title. Every row here is
        // already a label facing its own value ("Colors" -> "Light and dark,
        // 62 values"), so reprinting "Content"/"Details" above each of the
        // eleven rows on a phone is eleven stutters and no information.
        ...shareManifestRows().map((row) =>
          E("tr", { class: "tr" }, [
            E("td", { class: "td" }, [document.createTextNode(row.label)]),
            E("td", { class: "td", style: "color:var(--text-muted);" }, [
              document.createTextNode(row.detail),
            ]),
          ]),
        ),
      ]);

    let shareOpen = false;

    // The panel is rebuilt on every renderContent() -- a keystroke in the
    // search box, or a list fetch landing late -- so the nodes that hold user
    // state (the three fields, the error line, the button's disabled flag) are
    // created ONCE here and re-parented by buildSharePanel. Constructing them
    // inside the builder silently threw away a half-typed name and description,
    // and handed a mid-flight publish a second, freshly enabled button.
    const nameInput = E("input", {
      type: "text",
      class: "cbi-input-text",
      maxlength: 60,
      placeholder: _("Give it a name"),
    });
    const descInput = E("textarea", {
      class: "cbi-input-textarea",
      rows: 3,
      maxlength: 500,
      placeholder: _("One line about where this configuration fits."),
    });
    // Only ever shown while the creator account has no name yet. Not seeded
    // from anywhere local: the hub owns the name, and a cached copy would go
    // stale the moment it is changed from another browser.
    const nicknameInput = E("input", {
      type: "text",
      class: "cbi-input-text",
      maxlength: 40,
      placeholder: _("The name your shares are signed with"),
    });

    const errEl = E("p", {
      style: "color:var(--danger);font-weight:600;display:none;margin:0 0 0.6em;",
    });

    const showError = (message) => {
      errEl.textContent = message;
      errEl.style.display = "block";
    };

    const submitBtn = E(
      "button",
      { type: "button", class: "btn cbi-button-action important" },
      _("Publish"),
    );

    const doSubmit = () => {
      const name = nameInput.value.trim();
      if (!name) {
        showError(_("Please enter a name."));
        return;
      }

      const description = descInput.value.trim();
      const wantedNickname = profile.nickname ? "" : nicknameInput.value.trim();
      if (!profile.nickname && !wantedNickname) {
        showError(_("Choose the name to publish under."));
        return;
      }

      errEl.style.display = "none";
      submitBtn.disabled = true;

      // Two calls on purpose. The signature is account state, so it is
      // claimed first and the publish itself carries no author at all. If the
      // name turns out to be taken, nothing has been published yet and the
      // user simply picks another.
      const claim = wantedNickname
        ? L.resolveDefault(hubApi.callHubSetNickname(wantedNickname), null).then((res) => {
            const data = (res && res.result === 0 && res.data) || null;
            if (data && !data.error) {
              profile = { id: data.id, nickname: data.nickname };
              return true;
            }
            showError(
              data ? nicknameErrorMessage(data.error) : shareErrorMessage(res && res.error),
            );
            return false;
          })
        : Promise.resolve(true);

      claim.then((claimed) => {
        if (!claimed) {
          submitBtn.disabled = false;
          return;
        }
        L.resolveDefault(hubApi.callHubShare(name, description), null).then((res) => {
          if (res && res.result === 0) {
            // The one moment the warning is worth reading: the user has just
            // acquired something they can lose.
            ui.addNotification(
              null,
              E(
                "p",
                {},
                keySaved
                  ? _("Published.")
                  : _("Published. Your creator account lives only on this router — back up the key so a reflash can't take it."),
              ),
              "info",
            );
            shareOpen = false;
            // The button stays disabled until the panel is off screen --
            // re-enabling it here would leave a live Publish button up for the
            // whole my-shares round trip, and a second click would post the
            // same configuration twice. The draft is cleared at the same time
            // so reopening the panel starts fresh rather than re-offering what
            // was just published.
            refreshMyShares().then(() => {
              nameInput.value = "";
              descInput.value = "";
              nicknameInput.value = "";
              submitBtn.disabled = false;
              renderContent();
            });
          } else {
            submitBtn.disabled = false;
            showError(shareErrorMessage(res && res.error));
          }
        });
      });
    };

    // Identity is asked for once. After that it is shown, not re-typed:
    // re-offering a filled-in box on every publish suggests the signature is
    // per-config, which is exactly what this stopped being.
    const promptRename = () => {
      const input = E("input", {
        type: "text",
        class: "cbi-input-text",
        maxlength: 40,
        value: profile.nickname || "",
      });
      const err = E("p", {
        style: "color:var(--danger);font-weight:600;display:none;margin:0.6em 0 0;",
      });

      ui.showModal(_("Change your name"), [
        E(
          "p",
          {},
          _("This name signs everything you have published, including what is already in the store."),
        ),
        input,
        err,
        buildConfirmActions(() => {
          const next = input.value.trim();
          if (!next) {
            err.textContent = _("Pick a name between 1 and 40 characters.");
            err.style.display = "block";
            return;
          }
          L.resolveDefault(hubApi.callHubSetNickname(next), null).then((res) => {
            const data = (res && res.result === 0 && res.data) || null;
            if (data && !data.error) {
              ui.hideModal();
              refreshMyShares().then(renderContent);
              return;
            }
            err.textContent = data
              ? nicknameErrorMessage(data.error)
              : shareErrorMessage(res && res.error);
            err.style.display = "block";
          });
        }, _("Save")),
      ]);
    };

    submitBtn.addEventListener("click", doSubmit);

    // Before the account has a name: an input. After: the signature it will
    // carry, plus a way to change it. The short id is shown here (and in the
    // detail drawer) rather than on cards -- names are unique, so a number on
    // every card would be noise, but it is what lets someone prove which
    // "Eamon" they are.
    const buildIdentityField = (field) => {
      if (!profile.nickname) return field(_("Publish as"), nicknameInput);

      return E("div", { class: "aurora-store-field" }, [
        E("label", {}, _("Publish as")),
        E("div", {}, [
          E("strong", {}, [document.createTextNode(profile.nickname)]),
          E("span", { style: "color:var(--text-muted);margin-left:0.5em;" }, [
            document.createTextNode("#" + (profile.id || "")),
          ]),
          " ",
          E(
            "button",
            { type: "button", class: "cbi-button", click: () => promptRename() },
            _("Change"),
          ),
        ]),
      ]);
    };

    const buildSharePanel = () => {
      const field = (label, control) =>
        E("div", { class: "aurora-store-field" }, [
          E("label", {}, label),
          control,
        ]);

      const manifestTable = buildManifestTable();

      return E("div", { class: "aurora-store-share" }, [
        E("div", { class: "aurora-store-share-head" }, [
          E("h4", { style: "margin:0;" }, _("Publish current configuration")),
          E(
            "button",
            {
              type: "button",
              class: "cbi-button",
              click: () => {
                shareOpen = false;
                renderContent();
              },
            },
            _("Cancel"),
          ),
        ]),
        E("div", { class: "aurora-store-share-cols" }, [
          E("div", { class: "aurora-store-share-prev" }, [
            E("div", { class: "aurora-store-prev" }, [
              buildDuo(
                {
                  light: {
                    bg: uci.get("aurora", "theme", "light_bg"),
                    surface: uci.get("aurora", "theme", "light_surface"),
                    text: uci.get("aurora", "theme", "light_text"),
                    brand: uci.get("aurora", "theme", "light_brand"),
                  },
                  dark: {
                    bg: uci.get("aurora", "theme", "dark_bg"),
                    surface: uci.get("aurora", "theme", "dark_surface"),
                    text: uci.get("aurora", "theme", "dark_text"),
                    brand: uci.get("aurora", "theme", "dark_brand"),
                  },
                },
                { nav: currentNav },
              ),
            ]),
            E(
              "p",
              { style: "font-size:0.75em;color:var(--text-muted);text-align:center;margin:6px 0 0;" },
              _("How it looks in the store"),
            ),
          ]),
          E("div", {}, [
            field(_("Name"), nameInput),
            field(_("Description"), descInput),
            buildIdentityField(field),
            errEl,
          ]),
        ]),
        E("h4", { style: "margin:1.2em 0 0.4em;" }, _("What gets shared")),
        manifestTable,
        E(
          "p",
          { style: "color:var(--text-muted);font-size:0.8em;margin-top:0.8em;" },
          _("Anyone who applies this gets all of it. You can update or remove it later."),
        ),
        E("div", { class: "right", style: "margin-top:1em;" }, [submitBtn]),
      ]);
    };

    // ------------------------------------------------------------------
    // Header: search + tabs + share

    // count 是惰性的:builtinItems 在渲染前就定好了,myShares 要等 hub_my_shares
    // 回来。两个都读的是渲染那一刻的值,而不是定义这张表时的值。
    const TABS = [
      { key: "all", label: _("All") },
      { key: "builtin", label: _("Built-in"), count: () => builtinItems.length },
      { key: "hot", label: _("Hot") },
      { key: "new", label: _("New") },
      { key: "mine", label: _("My Shares"), count: () => myShares.length },
    ];

    const renderTabLabel = (tab) => {
      const btn = tabButtons[tab.key];
      if (!btn) return;
      while (btn.firstChild) btn.removeChild(btn.firstChild);
      btn.appendChild(document.createTextNode(tab.label));
      const n = tab.count ? tab.count() : 0;
      if (n) btn.appendChild(E("span", { class: "n" }, [document.createTextNode(String(n))]));
    };

    const tabButtons = {};
    const tabsEl = E(
      "div",
      { class: "aurora-store-filters" },
      TABS.map((tab) => {
        const btn = E("button", { type: "button", click: () => selectTab(tab.key) });
        tabButtons[tab.key] = btn;
        return btn;
      }),
    );
    TABS.forEach(renderTabLabel);

    const searchInput = E("input", {
      type: "text",
      class: "cbi-input-text",
      placeholder: _("Search themes or authors…"),
    });
    searchInput.addEventListener("input", () => {
      state.query = searchInput.value.trim().toLowerCase();
      renderContent();
    });

    const shareBtn = E(
      "button",
      {
        type: "button",
        class: "cbi-button cbi-button-add",
        click: () => {
          shareOpen = true;
          selectTab("mine");
        },
      },
      _("Share My Configuration"),
    );

    const titleEl = E("h2", {}, _("Theme Store"));

    const headEl = E("div", {}, [
      E("div", { class: "aurora-store-head" }, [
        titleEl,
        // Pushes search + share to the right on a desktop; the mobile rule
        // drops it, so the two controls take full rows instead of being
        // squeezed against a spacer that has nothing left to push.
        E("span", { class: "sp" }),
        searchInput,
        shareBtn,
      ]),
      bannerEl,
      tabsEl,
    ]);

    // ------------------------------------------------------------------
    // Content sections

    const matchesQuery = (name, author) => {
      if (!state.query) return true;
      return (
        (name || "").toLowerCase().includes(state.query) ||
        (author || "").toLowerCase().includes(state.query)
      );
    };

    const buildBuiltinGrid = () => {
      const items = builtinItems.filter((preset) =>
        matchesQuery(preset.label, "Aurora"),
      );
      if (!items.length) return null;
      return E(
        "div",
        { class: "aurora-store-grid" },
        items.map((preset) => buildBuiltinCard(preset)),
      );
    };

    const buildOnlineGrid = (sort) => {
      const grid = E("div", { class: "aurora-store-grid", id: "hub-cards" });
      const items = state.online[sort];

      if (state.onlineFailed && !items) {
        grid.appendChild(
          E(
            "div",
            {
              style:
                "grid-column:1/-1;text-align:center;color:var(--text-muted);padding:2em 1em;",
            },
            [
              E("p", {}, _("Unable to reach the theme store right now.")),
              E(
                "button",
                {
                  type: "button",
                  class: "cbi-button cbi-button-apply",
                  click: () => fetchSort(sort),
                },
                _("Retry"),
              ),
            ],
          ),
        );
        return grid;
      }

      if (!items) {
        grid.appendChild(
          E(
            "p",
            {
              class: "spinning",
              style: "grid-column:1/-1;padding:1.5em 0;",
            },
            _("Loading…"),
          ),
        );
        fetchSort(sort);
        return grid;
      }

      const visible = items
        .filter((item) => !isBuiltinSeed(item))
        .filter((item) => matchesQuery(item.name, item.author));

      if (!visible.length) {
        grid.appendChild(
          E(
            "div",
            {
              style:
                "grid-column:1/-1;text-align:center;color:var(--text-muted);padding:2em 1em;",
            },
            state.query
              ? _("No themes match your search.")
              : _("No configs here yet — go share the first one."),
          ),
        );
        return grid;
      }

      visible.forEach((item) => grid.appendChild(buildOnlineCard(item)));
      return grid;
    };

    const buildStaleNotice = () =>
      state.showingStale
        ? E(
            "em",
            {
              style:
                "display:block;color:var(--text-muted);font-size:0.85em;margin-top:0.5em;",
            },
            _("Showing a saved copy — reconnecting…"),
          )
        : null;

    const renderContent = () => {
      while (contentEl.firstChild) contentEl.removeChild(contentEl.firstChild);
      const push = (node) => node && contentEl.appendChild(node);

      if (state.tab === "all" || state.tab === "builtin") {
        const builtinGrid = buildBuiltinGrid();
        if (builtinGrid) {
          push(buildSectionTitle(_("Built-in"), _("Ships with the theme, works offline")));
          push(builtinGrid);
        }
      }

      if (state.tab === "all") {
        push(buildSectionTitle(_("Community"), _("Shared by other people")));
        push(buildStaleNotice());
        push(buildOnlineGrid("hot"));
      } else if (state.tab === "hot" || state.tab === "new") {
        push(buildStaleNotice());
        push(buildOnlineGrid(state.tab));
      } else if (state.tab === "mine") {
        if (shareOpen) push(buildSharePanel());
        else
          push(
            E("div", { style: "margin-top:1em;" }, [
              E(
                "button",
                {
                  type: "button",
                  class: "cbi-button cbi-button-add",
                  click: () => {
                    shareOpen = true;
                    renderContent();
                  },
                },
                _("Publish current configuration"),
              ),
            ]),
          );
        push(buildSectionTitle(_("My Shares"), ""));
        const keyBar = buildKeyBar();
        if (keyBar) push(keyBar);
        push(mySharesEl);
      }
    };

    const selectTab = (key) => {
      state.tab = key;
      TABS.forEach((tab) =>
        tabButtons[tab.key].classList.toggle("active", tab.key === key),
      );
      renderContent();
    };

    // ------------------------------------------------------------------
    // Online data lifecycle: instant paint from cache, reconcile with the
    // network, degrade to the built-in group plus a retry notice on failure.

    const applyResult = (res, sort) => {
      if (res && res.result === 0 && res.data) {
        if (sort === "hot") hubApi.listCache.set(res.data);
        state.online[sort] = Array.isArray(res.data.items) ? res.data.items : [];
        state.onlineFailed = false;
        state.showingStale = false;
        renderContent();
        return;
      }

      const stale = sort === "hot" ? hubApi.listCache.getStale() : null;
      if (stale && Array.isArray(stale.items) && stale.items.length) {
        state.online.hot = stale.items;
        state.showingStale = true;
      } else {
        state.onlineFailed = true;
      }
      renderContent();
    };

    const fetchSort = (sort) =>
      L.resolveDefault(hubApi.callHubList(sort, 1), null).then((res) =>
        applyResult(res, sort),
      );

    // ------------------------------------------------------------------
    // Boot: cached hot list first (even stale), then reconcile with the
    // fetch load() already ran.

    const cached = hubApi.listCache.getStale();
    if (cached && Array.isArray(cached.items) && cached.items.length)
      state.online.hot = cached.items;

    renderBanner();
    // 缓存或 null。null 走空态,不是错误态 —— 一台刚装好的路由器本来就没有
    // 已发布的作品,和"拿不到数据"是两回事。
    applyMe(hubApi.meCache.getStale());
    selectTab("all"); // 末行已 renderContent(),首帧在此成型

    [
      styleEl,
      headEl,
      contentEl,
      drawerMask,
      drawerEl,
    ].forEach((child) => rootEl.appendChild(child));

    // 网络在 DOM 挂载之后才发起。此刻画面已经成型:内置预设来自随包的
    // presets.json,在线列表与创作者档案来自上面两处缓存。两个请求回来后
    // 各自 reconcile,失败则保留当前这帧。
    fetchSort("hot");
    refreshMyShares();

    return rootEl;
  },
});
