#!/bin/sh /etc/rc.common
START=99

get_config()
{
	config_get_bool enable "$1" enable 0
}

run_qBittorrentEE()
{
	local enable
	config_get_bool enable "$1" enable

	if [ $enable ]; then
		local profile_dir
		local port
		config_get profile_dir "$1" profile_dir
		config_get port "$1" port
		qbittorrent-nox -d --profile="$profile_dir" --webui-port="$port"
	fi
}

start()
{
	stop
	local profile_path
	config_load "qBittorrentEE"
	config_foreach get_config "qBittorrentEE"
	[ $enable -eq 0 ] && exit 0
	config_foreach run_qBittorrentEE "qBittorrentEE"
}

stop()
{
	killall "qbittorrent-nox" >/dev/null 2>&1
}
