#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Tano >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Tano=/luci-static/tano
		set luci.main.mediaurlbase=/luci-static/tano
		commit luci
	EOF
fi

exit 0
