// Vendor the color-token engine from the @eamonxg/aurora-tokens npm package
// (published from the standalone aurora-tokens repo; independent semver).
//
// Refreshes:
//   - htdocs/luci-static/resources/utils/tokens.global.js  (the package's
//     prebuilt dist/tokens.global.js, copied verbatim)
//   - root/usr/share/aurora/color-tokens.conf              (shell key list,
//     derived from the vendored engine)
// then reruns scripts/gen-presets.mjs so the preset templates pick up the
// change. All vendored artifacts are committed; nothing downstream (CI, SDK
// build, device) needs npm or the theme repo.
//
// Source resolution:
//   1. --local <path>   build dist from a local aurora-tokens checkout --
//                       for iterating on an unreleased spec (run `npm
//                       install` there first)
//   2. npm registry     the version pinned in package.json devDependencies
//   3. sibling checkout ../aurora-tokens, as a fallback when the registry
//                       is unreachable or the version is unpublished
//
// Usage:  node scripts/sync-tokens.mjs [--local <path>]
//         node scripts/sync-tokens.mjs --check   exit 1 if outputs are stale
//
// Zero dependencies, same as gen-presets.mjs.

import {
  existsSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { resolve, dirname, relative, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const PACKAGE = "@eamonxg/aurora-tokens";
const TOKENS_GLOBAL = resolve(
  root,
  "htdocs/luci-static/resources/utils/tokens.global.js",
);
const TOKENS_CONF = resolve(root, "root/usr/share/aurora/color-tokens.conf");
const THEME_VIEW = resolve(
  root,
  "htdocs/luci-static/resources/view/aurora/theme.js",
);
const COLOR_GLOBAL = resolve(
  root,
  "htdocs/luci-static/resources/utils/color.global.js",
);
const check = process.argv.includes("--check");

const argValue = (flag) => {
  const index = process.argv.indexOf(flag);
  return index !== -1 ? process.argv[index + 1] : null;
};

const pinnedVersion = () =>
  JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"))
    .devDependencies[PACKAGE];

const buildFromCheckout = (checkout) => {
  const built = spawnSync(
    process.execPath,
    [resolve(checkout, "build-global.mjs")],
    { stdio: "inherit" },
  );
  if (built.status !== 0)
    throw new Error(
      `building dist in ${checkout} failed -- run \`npm install\` there first`,
    );
  return readFileSync(resolve(checkout, "dist/tokens.global.js"), "utf8");
};

const fetchFromRegistry = async (version) => {
  const tarballUrl = `https://registry.npmjs.org/${PACKAGE}/-/${PACKAGE.split("/")[1]}-${version}.tgz`;
  const response = await fetch(tarballUrl);
  if (!response.ok)
    throw new Error(`fetch ${tarballUrl}: HTTP ${response.status}`);
  const dir = mkdtempSync(join(tmpdir(), "aurora-tokens-"));
  const tarball = join(dir, "package.tgz");
  writeFileSync(tarball, Buffer.from(await response.arrayBuffer()));
  const extracted = spawnSync("tar", ["-xzf", tarball, "-C", dir], {
    stdio: "inherit",
  });
  if (extracted.status !== 0) throw new Error("tar extraction failed");
  return readFileSync(join(dir, "package/dist/tokens.global.js"), "utf8");
};

async function loadDist() {
  const explicit = argValue("--local");
  if (explicit) {
    console.log(`sync-tokens: source = local checkout ${explicit}`);
    return buildFromCheckout(explicit);
  }

  const version = pinnedVersion();
  try {
    const dist = await fetchFromRegistry(version);
    console.log(`sync-tokens: source = npm ${PACKAGE}@${version}`);
    return dist;
  } catch (error) {
    const sibling = resolve(root, "../aurora-tokens");
    if (existsSync(join(sibling, "build-global.mjs"))) {
      console.warn(
        `sync-tokens: WARNING registry unavailable (${error.message}); ` +
          `falling back to sibling checkout -- output may not match the ` +
          `pinned ${version}`,
      );
      return buildFromCheckout(sibling);
    }
    throw error;
  }
}

const dist = await loadDist();

// Derive the shell key list from the vendored engine itself, so the two
// artifacts cannot disagree.
const sandbox = { console };
vm.createContext(sandbox);
vm.runInContext(readFileSync(COLOR_GLOBAL, "utf8"), sandbox);
vm.runInContext(dist, sandbox);
const { INPUTS, DERIVED_KEYS } = sandbox.AuroraTokens;

const confSource = `# GENERATED by scripts/sync-tokens.mjs -- DO NOT EDIT.
# Ordered color token keys: ${INPUTS.length} editable inputs, then ${DERIVED_KEYS.length} engine-derived
# tokens (from ${PACKAGE}). Read at runtime by /usr/libexec/rpcd/luci.aurora
# for preset and import validation; each key exists as light_<key> and
# dark_<key> in UCI.
${Array.from(INPUTS).concat(Array.from(DERIVED_KEYS)).join("\n")}
`;

// Stamp the engine version into theme.js, which appends it as ?v= when
// loading tokens.global.js -- a version bump changes the URL, so browsers
// can never pair a new theme.js with an HTTP-cached engine (or vice versa).
const distVersion = dist.match(/@eamonxg\/aurora-tokens v(\S+)/)?.[1];
if (!distVersion)
  throw new Error("cannot find engine version in dist header");
const versionLine = `const TOKENS_ENGINE_VERSION = "${distVersion}";`;
const themeSource = readFileSync(THEME_VIEW, "utf8").replace(
  /const TOKENS_ENGINE_VERSION = "[^"]*";/,
  versionLine,
);
if (!themeSource.includes(versionLine))
  throw new Error("TOKENS_ENGINE_VERSION marker not found in theme.js");

const outputs = [
  [TOKENS_GLOBAL, dist],
  [TOKENS_CONF, confSource],
  [THEME_VIEW, themeSource],
];

let stale = false;
for (const [path, content] of outputs) {
  const name = relative(root, path);
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {}
  if (current === content) {
    console.log(`sync-tokens: ${name} up to date`);
    continue;
  }
  if (check) {
    console.error(
      `sync-tokens: ${name} is STALE -- run: node scripts/sync-tokens.mjs`,
    );
    stale = true;
    continue;
  }
  writeFileSync(path, content, "utf8");
  console.log(`sync-tokens: wrote ${name}`);
}

if (check) process.exit(stale ? 1 : 0);

// Preset templates embed engine output; refresh them from the new engine.
const presets = spawnSync(
  process.execPath,
  [resolve(here, "gen-presets.mjs")],
  { stdio: "inherit" },
);
process.exit(presets.status ?? 1);
